Feat: 부스 단건 삭제 API
Project-OpenBook/openbook-server pull request #122
Opened 2024-08-04 13:54 UTC by gitseoyeon

## Summary

- closed #119 
- 부스 개별 삭제가 가능한 API를 구현했습니다.
## Key Changes

- ManagerBoothController에  deleteBooth를 추가했습니다.
- ManagerBoothService에 부스를 제거하는 메서드를 추가했는데, 삭제하는 유저가 부스의 운영자인지 확인하는 checkUser메서드를 따로 만들어서 오류처리를 했습니다.
- 영속성 문제가 발생해서 Booth 엔터티에 따로 BoothArea를 일대다 매핑을 추가했습니다.
## Testing

- 삭제 됐을 경우
![image](https://github.com/user-attachments/assets/c999874c-ed74-46c9-ae97-27dc10287bad)
- 삭제한 부스를 다시 삭제할 경우
![image](https://github.com/user-attachments/assets/6cbda987-d773-457d-bc93-5d8345bd6123)

## To Reviewers

- 추가로 의견이나 질문 있으시면 말씀해주세요!

2024-08-05 01:13 UTC, muncool39 requested changes
확인했습니다 수고하셨습니다! 👍
코멘트로도 달았지만, 부스 구역까지 함께 삭제되는 부분을 수정하면 좋을 것 같습니다!
일단 생각나는 수정 방법도 함께 적었지만 다른 의견이나 생각나는 점 있으시면 같이 의견 나눠보고 방향을 결정해봐도 좋을 것 같습니다!

2024-08-05 01:13 UTC, muncool39 commented on src/main/java/com/openbook/openbook/booth/service/ManagerBoothService.java
> +    private void checkUser(User user, Booth booth){
메서드 명만 보면 뭘 체크하는지 알기 힘드니 same 등 단어를 추가해 메서드가 하는 역할을 정확하게 나타내도 좋을 것 같아요! 아니면 아직 로직이 재사용 되는 곳이 없기도 하니 deleteBooth 안에 넣어도 될 것 같기도 하네요

2024-08-05 01:13 UTC, muncool39 commented on src/main/java/com/openbook/openbook/booth/entity/Booth.java
> +    private List<BoothArea> boothAreas = new ArrayList<>();
저희가 부스 승인을 거절하면 연결된 부스는 해제하지 않고 상태만 바꾸는 걸로 기억하는데, 이렇게 할 경우에 아직 모집 중인 구역도 삭제될 수 있다는 생각이 듭니다! 구역 상태 변경 시 연결된 부스가 해제되도록 하면 좋을 것 같네요
또 배치도 구조에도 영향을 줄 수 있으니 cascade 설정을 바꿔 부스를 삭제해도 구역은 남아있게 하는 방법을 사용하거나, 위 상태 변경 시의  예시로 말한 방법처럼 부스 삭제 시에도 연결된 부스 구역과의 관계를 끊는 방법을 사용하면 어떨까요? 관계를 끊는 메서드를 만들어 두 경우에 공통으로 사용해도 좋을 것 같다는 생각도 듭니다! 
위 방법을 사용한다면 해당 매핑 코드를 삭제해도 부스 삭제가 정상적으로 이뤄질 것 같습니다!

2024-08-05 08:21 UTC, gitseoyeon commented
영속성 문제 때문에 단순히 매핑을 하면 된다 생각했는데 그렇게 되면 부스 제거를 할때 매핑된 부스 위치까지 제거 될 거라고 생각을 미처하지 못했습니다.....!!! 의견 주셔서 감사합니다 👍🏻 부스를 제거 할 때 공통 메서드를 만들어서 부스 위치 상태를 다시 empty로 변경하고 연결된 부스를 끊어서 제거하는 방향으로 수정했습니다! 수정 확인해주시면 감사하겠습니다~~

2024-08-06 01:16 UTC, muncool39 requested changes
확인했습니다~ 👍
처음 리뷰에 적은 내용으로, EventManagerBoothService 에서 승인 거절이 일어날 경우에도 구역에서 부스를 제거하는 메서드를 사용해야 될 것 같습니다! 
아래는 core의 BoothAreaService 안에 있는 코드입니다.
![image](https://github.com/user-attachments/assets/c4dc99c7-a840-4a37-b6a7-b57e5f7ab825)
이 것처럼 AreaService 안에 부스 연결을 해제하는 메서드를 따로 만들어 ManagerBooth, EventManagerBooth 서비스에서 호출해 사용하는 방식으로 구현하면 좋을 것 같아요~

추가적으로, 해당 부스를 삭제할 수 있는 조건에 대해 생각난 부분입니다!
- 승인되지 않은 부스는 바로 삭제 가능
- 승인 된 부스는 연결된 행사가 종료되었다면 삭제 가능

등의 삭제 조건이 있으면 어떨까요?

2024-08-06 01:16 UTC, muncool39 commented on src/main/java/com/openbook/openbook/booth/entity/BoothArea.java
>      }
부스를 삭제하는 작업만 한다면 따로 status를 받지 않아도 될 것 같습니다!

2024-08-06 01:16 UTC, muncool39 commented on src/main/java/com/openbook/openbook/booth/service/ManagerBoothService.java
> +    }
위에 작성한 코멘트와 비슷한 내용으로, AreaStatus를 다른 걸로 바꾸는 동작이라기 보다는 그냥 부스 구역에서 부스를 제거하는 행위이니 맞게 메서드 명을 변경해도 좋을 것 같습니다!

2024-08-06 01:16 UTC, muncool39 commented on src/main/java/com/openbook/openbook/booth/service/ManagerBoothService.java
> +        sameUser(user, booth);
sameUser() 메서드명만 보면 메서드가 하는 일이 뭔지 헷갈릴 수도 있다는 생각이 들었습니다!
제가 전에 리팩터링 관련 서적을 읽었었는데 정확한 문장은 기억나지 않지만 메서드가 하는 일이 나타나면 좋다는 내용의  글이였습니다! 엔티티를 찾아오는 메서드 명들을 get-OrException으로 정한 것을 예시로 들 수 있겠네요 😃 너무 긴 것도 좋진 않지만 그래도 의미가 정확하게 보이면 더 좋을 것 같다는 생각이 들었습니다! 
메서드 내용도 User와 User가 아니라 User와 Booth를 비교해 매니저인지 체크하는 내용이니 반영해서 생각해보면 좋을 것 같아요~!
지금 생각나지 않는다면 deleteBooth안에 넣어두고, 부스 수정 작업을 할 때 똑같은 동작이 수행될 테니 그때 리팩터링해 사용해보는 방법도 있을 것 같네요!

2024-08-07 06:02 UTC, gitseoyeon commented on src/main/java/com/openbook/openbook/booth/entity/BoothArea.java
>      }
엇 status를 따로 받지 않는다면 부스 구역 상태를 어떤 값으로 바꾸는 지에 대해서는 어떻게 전달하면 좋을까요?
현재는 부스가 신청상태에 놓였을 경우 WAITING으로 되어 있는데, 삭제를 하게 되면 EMPTY라는 상태를 받아야하지 않나요?!

2024-08-07 06:17 UTC, muncool39 commented on src/main/java/com/openbook/openbook/booth/entity/BoothArea.java
>      }
해당 메서드에 booth을 받지 않는 것처럼 delete 행위가 어차피 EMPTY로 고정이니 아예 매개변수로 받지 않아도 될 것 같다는 뜻이였습니다!
WAITING 에 대해 말씀하셔서 기존 코드 보니까 updateBooth를 사용해 상태랑 연결된 부스도 같이 업데이트 하던데, 부스를 삭제할 때도 메서드를 따로 만들지 않고 updateBooth에 EMPTY와 null을 넘겨서 공통으로 쓰면 좋을 것 같습니다~

2024-08-07 07:46 UTC, gitseoyeon commented
자세한 코멘트 남겨 주셔서 감사합니다!! 👍🏻
남겨주신 코멘트를 토대로 몇가지 수정 작업을 했습니다.
먼저 BoothArea 엔티티 안에 있던 삭제 메서드를 지우고 그전에 있던 updateBooth 를 재사용해서 empty 상태와 null을 파라미터로 넘겨 변하게 했습니다.

그리고 ManagerBoothService 안에 있던 changeAreaStatus 메서드를 지우고 boothAreaService에 disconnectBooth라는 부스 연결을 끊는 메서드를 만들어서 사용했습니다. (메서드명은 연결을 끊는다는 의미에서 지어 보았는데 더 좋은 메서드명 추천받습니다!)  

또, 원래 있었던 sameUser 메서드는 우선 deletebooth안에 넣어두었습니다. 추후 사용할 일이 있다면 메서드명 같이 고민해보고 빼면 될 것 같습니다!

추가로 의견 주신 것중에 승인된 부스일 경우 추가적인 삭제 조건도 따로 작성했습니다. 오류 반환은 우선 INVALID_PARAMETER로 주었는데 이걸로 해도 괜찮을 지 고민이 됩니다!

2024-08-08 14:48 UTC, muncool39 commented
확인했습니다! 오류 반환은 요청 자체는 할 수 있지만, 서버 규칙 상의 문제이기 때문에 CONFLICT 오류를 반환하도록 하면 좋을 것 같아요! 할 수 있는 기간이 아니라던가, 관맂

2024-08-10 12:36 UTC, gitseoyeon commented
오류 반환 의견 주셔서 감사합니다! 제가 생각했을 때도 '삭제 가능 기간이 아니다'라는 오류를 반환하는게 가장 직관적으로 보기 편할 듯 해서 '삭제 불가 기간' 이라는 의미로 오류를 반환 했습니다! 👍🏻

2024-08-10 13:56 UTC, muncool39 reviewed
확인했습니다! 👍 추가적으로 의견 남겼습니다!

2024-08-10 13:56 UTC, muncool39 commented on src/main/java/com/openbook/openbook/global/exception/ErrorCode.java
> +    DELETION_IMPOSSIBLE_PERIOD(HttpStatus.CONFLICT, "삭제 할 수 있는 기간이 아닙니다."),
다른 메세지들과 비슷하게 "삭제 가능한 기간이 아닙니다." 로 어감을 맞추는 건 어떨까요?

2024-08-10 13:56 UTC, muncool39 commented on src/main/java/com/openbook/openbook/global/exception/ErrorCode.java
> +    DELETION_IMPOSSIBLE_PERIOD(HttpStatus.CONFLICT, "삭제 할 수 있는 기간이 아닙니다."),
또 코드 명에 관련해서 너무 길면 Undeleted_Period 정도로 줄이는 방법도 있을 것 같네요!

2024-08-10 14:08 UTC, gitseoyeon commented on src/main/java/com/openbook/openbook/global/exception/ErrorCode.java
> +    DELETION_IMPOSSIBLE_PERIOD(HttpStatus.CONFLICT, "삭제 할 수 있는 기간이 아닙니다."),
Undeleted_Period도 충분히 의미가 담긴 표현이라고 생각되어 살짝 의미를 더 담아서 표현 해보면 UNDELETABLE_PERIOD 으로 사용 할 수 있을 것 같은데 어떠신가요?

2024-08-10 14:10 UTC, muncool39 commented on src/main/java/com/openbook/openbook/global/exception/ErrorCode.java
> +    DELETION_IMPOSSIBLE_PERIOD(HttpStatus.CONFLICT, "삭제 할 수 있는 기간이 아닙니다."),
의미가 더 명확해져서 좋은 것 같습니다! 👍

2024-08-10 14:19 UTC, gitseoyeon commented on src/main/java/com/openbook/openbook/global/exception/ErrorCode.java
> +    DELETION_IMPOSSIBLE_PERIOD(HttpStatus.CONFLICT, "삭제 할 수 있는 기간이 아닙니다."),
UNDELETABLE_PERIOD로 변경을 완료 했습니다! 다만 변경했을 때 다음 사진과 같은 밑줄이 그어지는데 rename to...를 눌러보아도 달라지는 게 없고 전반적으로 프로젝트 실행되는 부분이나 에러 사항에 대해서는 문제가 되지 않아 우선 수정을 했습니다!
![image](https://github.com/user-attachments/assets/1af3b08b-98c5-4c9f-880e-a44279aca25f)

2024-08-10 14:27 UTC, muncool39 approved these changes
수정 확인했습니다! 수고하셨습니다! 👍

2024-08-10 14:47 UTC, merged