Feat: 부스 예약 서비스 등록
Project-OpenBook/openbook-server pull request #139
Opened 2024-08-16 06:23 UTC by gitseoyeon

## Summary

- closed #133 

## Key Changes

- ManagerBoothController에 post 형식으로 부스 예약 서비스를 등록할 수 있는 api를 작성했습니다.
- 부스 예약 서비스를 신청할 경우 다음과 같은 조건에 만족해야합니다.
   예약 시간이 부스 운영 시간 안에 있는가 -> 운영시간 외의 시간에 등록하면 CONFLICT 에러
   새로운 예약 서비스를 등록하는가 -> 이미 등록된 예약 날짜와 시간대를 등록하면 CONFLICT 에러
- 같은 날짜에 새로운 시간을 추가하고 싶을 경우 같은 날짜로 등록된 boothReservation 객체를 찾아서 시간만 추가하게 했습니다.
## Testing

- 성공 시
<img width="1167" alt="image" src="https://github.com/user-attachments/assets/e90dd638-7334-430c-888b-1ed33bf84034">
- 이미 존재하는 예약 서비스를 등록할 경우
<img width="1141" alt="image" src="https://github.com/user-attachments/assets/92628db1-12bf-4941-aeed-9e34d146130c">
- 예약 불가능 시간대에 신청할 경우
<img width="1136" alt="image" src="https://github.com/user-attachments/assets/0adcc9f3-e109-4bd7-9636-fd0a78c21cef">

## To Reviewers

- Reservation이라는 한 단어가 길다보니 클래스명이나 메서드명을 지을 때 길어지게 되는데 정확한 의미를 담으려면 어쩔수 없는 부분인지, 편의상 좀 줄이는게 좋을지 고민이 되는데 의견 주시면 감사하겠습니다!
- 외에도 질문사항이나 의견 있으싯면 편하게 말씀해주세요!

2024-08-16 16:10 UTC, muncool39 requested changes
확인했습니다! 수고하셨습니다! 👍
클래스, 메서드 명에 관련해서는 생략 가능한 부분은 생략하는 것도 좋을 것 같아요! 
그 외로는 코멘트로도 남긴 내용이지만 처음 예약 정보를 등록하는 것이라면 date 가 이미 있는 경우도 예외로 처리해서 time 을 추가하거나 수정하는 기능을 분리해도 좋을 것 같습니다!

2024-08-16 16:10 UTC, muncool39 commented on src/main/java/com/openbook/openbook/booth/controller/request/ReservationRegistrationRequest.java
> +        @NotEmpty List<String> reservationDetailLists
시간을 어떤 포멧으로 넘기는지 궁금합니다!
그리고 시간이라는 의미만 나타내도 될 것 같아서 times 등으로 변수 명을 줄여도 될 것 같네요!

2024-08-16 16:10 UTC, muncool39 commented on src/main/java/com/openbook/openbook/global/exception/ErrorCode.java
> +    ALREADY_RESERVED_SERVICE(HttpStatus.CONFLICT, "이미 존재하는 예약 서비스 입니다."),
서비스라는 어감 대신 이미 존재하는 예약 시간, 날짜입니다 등은 어떨까요?

2024-08-16 16:10 UTC, muncool39 commented on src/main/java/com/openbook/openbook/booth/controller/ManagerBoothController.java
> +        return ResponseEntity.ok(new ResponseMessage("예약 서비스가 신청었습니다."));
예약 서비스를 신청하는 의미 보다 해당 api 자체가 예약 서비스 안에 들어간 예약 날짜를 추가하는 api 라는 것은 어떨까요?
예약 서비스 신청은 승인이나 거부 등이 이후 동작에 있는 상황에서 좋은 것 같은데 해당 기능은 서비스 신청보다는 단순히 예약 날짜를 추가하는 느낌이 강하다는 생각이 들어 말씀드려봅니다!

2024-08-16 16:10 UTC, muncool39 commented on src/main/java/com/openbook/openbook/booth/service/ManagerBoothService.java
> +                    .build();
dto 생성 시 Builder 대신 생성자를 사용해도 좋을 것 같습니다!
필드가 몇 없기도 해서 코드가 단축될 것 같습니다 😀

2024-08-16 16:10 UTC, muncool39 commented on src/main/java/com/openbook/openbook/booth/service/core/BoothReservationService.java
> +    }
일치하는 예약 정보가 없는 경우의 처리는 위에 hasExistDate 로 했기 때문에 생략하신 걸까요?!
추가로 Booth  오타가 있는 것 같습니다!

2024-08-16 16:10 UTC, muncool39 commented on src/main/java/com/openbook/openbook/booth/service/ManagerBoothService.java
> +    }
해당 코드를 date 가 없는 경우에는 date 를 먼저 생성하고 아닌 경우는 time 만 생성하는 내용이라고 이해했는데, 그럼 time 만 추가하고 싶은 경우에도 해당 api 를 호출하게 되는 걸까요?
만약 time 만 추가하고 싶은 경우에는 이미 생성된 BoothReservation 을 사용해 추가하는 것이 더 편할 것 같다는 생각이 들어서 질문드려봅니다! 
처음 등록만 하는 기능이라면 그냥 이미 생성된 날짜인 경우에 오류를 반환해도 될 것 같다는 생각이 들었습니다! 만약 이 방법을 사용한다면 detail 생성 처리도 더 간단해질 것 같아요 😃

2024-08-16 16:36 UTC, gitseoyeon commented on src/main/java/com/openbook/openbook/booth/controller/ManagerBoothController.java
> +        return ResponseEntity.ok(new ResponseMessage("예약 서비스가 신청었습니다."));
register라는 키워드를 사용한 이유는 의미 자체는 등록하다 라는 의미가 있어서 서비스를 등록한다는 느낌으로 사용했었습니다! responseMessage 같은 경우는 추가되었습니다 혹은 등록 되었습니다로 수정하는게 좋을 것 같아요!
저희가 어떤 서비스를 신청할 때는 register를 사용하기도 했으니 흐름상 신청한다는 의미로 보일 수도 있겠네요 😮
register 키워드 대신 상품 추가 처럼 add를 대신하는 게 좋을까요?!

2024-08-16 16:36 UTC, gitseoyeon commented on src/main/java/com/openbook/openbook/booth/controller/request/ReservationRegistrationRequest.java
> +        @NotEmpty List<String> reservationDetailLists
시간은 13:00와 같이 보내는 걸로 했습니다!
변수명 추천 감사합니다!

2024-08-16 16:36 UTC, gitseoyeon commented on src/main/java/com/openbook/openbook/booth/service/ManagerBoothService.java
> +                    .build();
조언 감사합니다! 적용해보고 다시 올려보도록 하겠습니다~~

2024-08-16 16:36 UTC, gitseoyeon commented on src/main/java/com/openbook/openbook/booth/service/ManagerBoothService.java
> +    }
넵 지금 현재 구현한 상황에서는 시간만 추가하고 싶을 경우에도 현 api를 불러오도록 하게 되어있습니다!
제가 테스트를 해보면서 같은 날짜에 시간만 추가했을 경우 새로운 id를 가진 reservation이 생겨버리는 문제 때문에 추가해뒀었습니다. 말씀하신 것처럼 처음에는 오류 처리를 하고 추가 할 수 있게 하는게 더 나중에 기능적으로 효율적이겠네요!

2024-08-16 16:36 UTC, gitseoyeon commented on src/main/java/com/openbook/openbook/booth/service/core/BoothReservationService.java
> +    }
넵 hasExistDate에서 이미 예약 정보가 있음을 조건문에서 판별 한 후 해당 메서드를 실행하는 것이기 때문에 따로 구현해두지는 않았습니다!
오타는 수정하겠습니다!

2024-08-16 16:36 UTC, gitseoyeon commented on src/main/java/com/openbook/openbook/global/exception/ErrorCode.java
> +    ALREADY_RESERVED_SERVICE(HttpStatus.CONFLICT, "이미 존재하는 예약 서비스 입니다."),
서비스를 붙인 이유는 예약이라는 키워드만 단순히 붙였을 경우 부스 구역 예약과 의미가 겹칠 것 같아서였습니다!
말씀 하신 것처럼 서비스라는 키워드를 지워도 ALREADY_RESERVED_SERVICE 로 의미 혼돈이 크게 없을 수도 있겠네요!

2024-08-16 16:41 UTC, muncool39 commented on src/main/java/com/openbook/openbook/booth/controller/ManagerBoothController.java
> +        return ResponseEntity.ok(new ResponseMessage("예약 서비스가 신청었습니다."));
앗 일단 해당 코멘트는 ResponseMessage 를 보고 작성했었습니다! add 도 의미 상 괜찮을 것 같네요! 👍

2024-08-17 03:18 UTC, muncool39 requested changes
확인했습니다! 👍
코멘트로도 달았지만 date 가 이미 있는 경우 무조건 오류를 발생시키면 time 유무 검사 과정은 필요하지 않기 때문에 해당 기능에서 제외하는 것이 좋을 것 같아요! 😃 
수정 api 를 개발할 때 예약 id + 시간으로 time 을 검사하도록 하면 좋을 것 같습니다 !

2024-08-17 03:18 UTC, muncool39 commented on src/main/java/com/openbook/openbook/booth/service/ManagerBoothService.java
> +            throw new OpenBookException(ErrorCode.ALREADY_RESERVED_DATE);
date 가 이미 존재하면 무조건 에러를 반환하기 때문에 time이 존재하는지 확인하는 과정을 없애도 될 것 같습니다!

2024-08-17 03:18 UTC, muncool39 commented on src/main/java/com/openbook/openbook/booth/service/ManagerBoothService.java
> +        } else {
위에서 바로 에러를 반환한다면 else 문을 사용하지 않도록 변경해도 좋을 것 같습니다!

2024-08-17 05:29 UTC, gitseoyeon commented on src/main/java/com/openbook/openbook/booth/service/ManagerBoothService.java
> +            throw new OpenBookException(ErrorCode.ALREADY_RESERVED_DATE);
이 에러 반환에 있어서는 아예 날짜와 시간을 같은 데이터로 주었을 경우와 날짜만 같은 데이터로 주었을 경우를 세분화해서 에러 메세지를 만들었었습니다!
만약에 말씀하신 대로 동일한 date가 존재했을 때 무조건 같은 에러 메세지를 반환할 경우 ALREADY_RESERVED_SERVICE 로 통일 해야할 것 같은데 어떻게 생각하시나요?!

2024-08-17 06:45 UTC, muncool39 commented on src/main/java/com/openbook/openbook/booth/service/ManagerBoothService.java
> +            throw new OpenBookException(ErrorCode.ALREADY_RESERVED_DATE);
이 경우에는 그냥 ALREADY_RESERVED_DATE 를 반환하면 될 것 같다는 생각이 들었습니다!

일단 제가 생각한 것은 해당 기능이 예약 정보를 처음 등록하는 api 라서 boothReservation 를 처음 생성한다고 생각하는데
그래서 지금처럼 받은 date와 일치하는 boothReservation 안에서 중복되는 time을 찾을 필요가 없다고 생각했습니다! 어차피 date 를 처음 생성하는 것이니 해당 date 에 time이 있을 수가 없으니까요

중복 체크를 한다면 DATE 오류 반환 이후에 time 리스트 안에 String 끼리만 체크하면 될 것 같습니다! 오류를 세분화 한다면 이때의 오류 메세지를 "중복되는 시간이 있습니다" 등으로 다르게 하면 될 것 같아요 ! 😃

2024-08-17 08:01 UTC, gitseoyeon commented
친절한 코멘트 감사합니다!! 남겨주신 피드백을 반영해서 우선 같은 날짜의 데이터를 입력 할 경우 무조건 ALREADY_RESERVED_DATE 오류를 반환하도록 했습니다! 추가로 처음에 시간을 입력했을 때  입력한 시간중 중복된 시간을 전달했을 경우의 오류 처리를 추가했습니다! 확인해보시면 좋을 것 같습니다 😊

![image](https://github.com/user-attachments/assets/2492baf8-3388-4422-8342-b13745115d0b)

2024-08-17 13:47 UTC, muncool39 requested changes
확인했습니다 ! 👍
코멘트에도 작성한 내용이지만 사용하지 않게 된 메서드들이 있다면 제거해도 좋을 것 같네요! 그 외에도 몇 가지 의견 적었습니다!

2024-08-17 13:47 UTC, muncool39 commented on src/main/java/com/openbook/openbook/booth/service/ManagerBoothService.java
> +    private Set<String> getValidTimesOrException(List<String> times) {
반환되는 Set이 사용되고 있지 않는데, void 를 사용하는 것은 어떨까요?

2024-08-17 13:47 UTC, muncool39 commented on src/main/java/com/openbook/openbook/booth/service/ManagerBoothService.java
> +        }
time 유효성보다 date 가 이미 있는 경우를 먼저 체크해도 될 것 같습니다!

2024-08-17 13:47 UTC, muncool39 commented on src/main/java/com/openbook/openbook/booth/service/core/BoothReservationDetailService.java
> +    }
사용하지 않게 된 메서드는 제거해도 좋을 것 같습니다!

2024-08-17 14:24 UTC, gitseoyeon commented on src/main/java/com/openbook/openbook/booth/service/ManagerBoothService.java
> +    private Set<String> getValidTimesOrException(List<String> times) {
앗 이부분은 전에 중복되는 tag 데이터 판별하는 메서드 참고하면서 가져온 메서드라 제가 수정을 마저 못했네요 수정하겠습니다 😅

2024-08-17 14:30 UTC, gitseoyeon commented
말씀해주신 수정사항 모두 수정 마쳤습니다!

2024-08-18 09:54 UTC, muncool39 approved these changes
변경 확인했습니다! 고생하셨습니다 ~! 👍

2024-08-18 10:37 UTC, merged