Feat: 부스별 저장된 예약 정보 목록 조회
Project-OpenBook/openbook-server pull request #187
Opened 2024-08-31 16:29 UTC by gitseoyeon

## Summary

- closed #176 
- GET /{booth_id}/reservations

## Key Changes

- BoothReservationsResponse 생성
- BoothReservationDetalResponse를 생성해서 BoothReservationsResponse 안에 리스트 형식으로 불러왔습니다.
-  BoothReservationRespository에 부스에 저장된 예약 정보를 불러오는 메서드를 생성했습니다. 불러온 예약 정보를 이용해서 BoothReservationDetailRespository에서 예약 상세 정보를 불러왔습니다.
## Testing

- 성공 시
![image](https://github.com/user-attachments/assets/e1c48172-5bc6-4077-bcf3-6c7d4fb236e8)

## To Reviewers

- 현재는 부스 예약상세정보들을 리스트 형식으로 다 불러오게 했습니다. 추후 필요시 데이터를 잘라서 불러오도록 작업하겠습니다.
- 예약 상세 정보를 불러올 때 예약자 정보도 불러오는 것이 좋을까요? 우선 제외시켜두었는데 넣어도 상관 없을 것 같다는 생각도 드네요!
- 그 외에 질문사항이나 의견 있으시면 리뷰 남겨주세요 ! 😊

2024-09-01 06:10 UTC, muncool39 requested changes
확인했습니다! 😃 예약 목록은 list로 한번에 보게 하는 것도 좋다고 생각해요!
예약자 정보에 대해서는 해당 부스의 관리자만 볼 수 있도록 하는 것이 좋을 것 같다는 생각이 들었습니다! 
그 외 궁금한 점 등 코멘트 남겼습니다!

2024-09-01 06:10 UTC, muncool39 commented on src/main/java/com/openbook/openbook/booth/repository/BoothReservationRepository.java
> +    List<BoothReservation> findBoothReservationByLinkedBooth(Booth booth);
성능 개선을 위해 id로 찾는 것은 어떨까요?

2024-09-01 06:10 UTC, muncool39 commented on src/main/java/com/openbook/openbook/booth/service/core/BoothReservationService.java
해당 클래스가 core 클래스라서 현재 저희 프로젝트 패키지 규칙 상 검증이 필요한 내용은 상위 클래스 (ex common/CommonReservationService) 에서 하고 해당 클래스에서는 BoothReservationDetailService 에 구현하신 것처럼 엔티티를 받아오는 내용만 포함되도록 하면 좋을 것 같아요!

2024-09-01 06:10 UTC, muncool39 commented on src/main/java/com/openbook/openbook/booth/service/core/BoothReservationService.java
> +        Booth booth = boothService.getBoothOrException(boothId);
부스가 승인된 상태인지 확인하지 않아도 될까요?!

2024-09-01 06:10 UTC, muncool39 commented on src/main/java/com/openbook/openbook/booth/controller/response/BoothReservationsResponse.java
> +        long boothManagerId
매니저 아이디를 포함한 이유가 따로 있으실까요?

2024-09-01 06:10 UTC, muncool39 commented on src/main/java/com/openbook/openbook/booth/controller/response/BoothReservationsResponse.java
> +        String date,
필수 정보인 date 가 앞쪽에 존재해도 좋을 것 같네요!

2024-09-01 14:04 UTC, gitseoyeon commented on src/main/java/com/openbook/openbook/booth/repository/BoothReservationRepository.java
> +    List<BoothReservation> findBoothReservationByLinkedBooth(Booth booth);
사실 그것도 고민을 했었는데 쿼리를 직접 만들어서 사용하는 것 보다 쿼리메서드를 사용하는게 더 성능상 좋을까 싶어서 저렇게 했던건데 알아보니 둘다 그렇게 차이는 없었네요!! 말씀하신 것처럼 id로 찾는게 더 나을 것 같네요! 수정하겠습니다 👍🏻

2024-09-01 14:13 UTC, gitseoyeon commented on src/main/java/com/openbook/openbook/booth/service/core/BoothReservationService.java
> +        Booth booth = boothService.getBoothOrException(boothId);
앗 그 부분을 생각 못하고 있었네요! 다시 추가하겠습니다~~

2024-09-01 14:14 UTC, gitseoyeon commented on src/main/java/com/openbook/openbook/booth/controller/response/BoothReservationsResponse.java
> +        long boothManagerId
로그인한 유저가 해당 부스의 담당자인지 파악하기 위해 넣어두었습니다! 추후 필요할 듯 싶어 넣어 두었는데 사용할 일이 적을까요?!

2024-09-01 14:15 UTC, gitseoyeon commented on src/main/java/com/openbook/openbook/booth/controller/response/BoothReservationsResponse.java
> +        String date,
date와 time 정보가 같이 붙어 있으면 좋을 듯 싶어서 저렇게 두었는데 그러면 date와 details 를 앞으로 보낼까요?!

2024-09-01 14:43 UTC, muncool39 commented on src/main/java/com/openbook/openbook/booth/controller/response/BoothReservationsResponse.java
> +        long boothManagerId
앗 이해했습니다! 괜찮다고 생각합니다!

2024-09-01 15:01 UTC, gitseoyeon commented
말씀 해주신 것 처럼 쿼리메서 드 및 서비스 분리작업과 오류 처리, 응답 데이터 순서 수정을 했습니다!
응답 순서는 일단 id, name, description이 붙어 있으면 좋을 것 같아 앞에 두었고 그 뒤에 date와 details를 두고 그 뒤에 price와 imageUrl, managerId 값을 두도록 했습니다!
다음은 수정했을 때 응답 되는 결과 입니다.
<img width="565" alt="image" src="https://github.com/user-attachments/assets/78c887f0-d673-4283-a59f-e0cc71a40714">
예약자의 정보는 부스 관리자만 보이도록 하기 위해서는 API를 따로 만들어서 구현하는게 좋을까요?!

2024-09-02 00:25 UTC, muncool39 reviewed
확인했습니다! 변경 수고하셨습니다👍 추가로 약간의 코멘트 남겼습니다!
말씀하신 것처럼 예약자 정보를 확인하는 API 는 관리자용으로 따로 개발 진행하면 좋을 것 같네요. 이 부분은 저도 고민해볼게요!

2024-09-02 00:25 UTC, muncool39 commented on src/main/java/com/openbook/openbook/booth/repository/BoothReservationDetailRepository.java
> +    List<BoothReservationDetail> findBoothReservationDetailsByLinkedReservation(BoothReservation boothReservation);
해당 부분도 Id 로 조회하는 것은 어떨까요?

2024-09-02 00:25 UTC, muncool39 commented on src/main/java/com/openbook/openbook/booth/service/common/CommonReservationService.java
> +        for(BoothReservation boothReservation : boothReservations){
코드 길이를 줄이기 위해 이 부분의 boothReservation을 reservation 정도로 줄이는 건 어떻게 생각하실까요?

2024-09-02 06:14 UTC, gitseoyeon commented on src/main/java/com/openbook/openbook/booth/service/common/CommonReservationService.java
> +        for(BoothReservation boothReservation : boothReservations){
리스트명과 for문 모두를 말씀하시는 건가요?!

2024-09-02 06:16 UTC, muncool39 commented on src/main/java/com/openbook/openbook/booth/service/common/CommonReservationService.java
> +        for(BoothReservation boothReservation : boothReservations){
앗 for문에 대한 의견이였습니다!

2024-09-02 06:20 UTC, gitseoyeon commented on src/main/java/com/openbook/openbook/booth/service/common/CommonReservationService.java
> +        for(BoothReservation boothReservation : boothReservations){
넵넵 좋습니다 👍🏻

2024-09-02 06:31 UTC, gitseoyeon commented
넵!! 말씀하신내용 토대로 반영해서 수정 했습니다!

2024-09-02 06:35 UTC, muncool39 approved these changes
변경 확인했습니다! 수고하셨습니다 ~👍

2024-09-02 06:38 UTC, merged