Feat/#194
Project-OpenBook/openbook-server pull request #203
Opened 2024-09-07 15:22 UTC by gitseoyeon

## Summary

- closed #194 
PUT booths/reserve/{detail_id}
## Key Changes

- BoothReservationDetailService에서 setUserToReservation메서드를 만들어서 예약 상세 객체를 불러와서 상태를 수정하는 작업을 했습니다.
- getReservationDetail를 통해 찾으려는 부스 상세 객체의 예약 상태와 존재 여부를 판단하고 조회할 수 있게 했습니다.
- ErrorCode에 ALREADY_RESERVED_SERVICE라는 에러 메세지를 추가했습니다. 이는 이미 예약된 서비스에 사용자가 예약하려고 하는 경우에 반환됩니다.
- BoothReservationDetail 엔티티에 updateUser라는 메서드를 만들어서 user와 status 정보를 update 할 수 있게 구현했습니다.
## Testing

- 성공 시
![image](https://github.com/user-attachments/assets/d522a7e1-337d-41af-af18-a385085675ae)
![image](https://github.com/user-attachments/assets/8182a4e2-192e-49dd-a832-c4308b7aa368)
- 이미 예약된 서비스를 예약하고자 할 경우
![image](https://github.com/user-attachments/assets/9312ebae-fc17-4abd-be31-09d803934dc5)
- 존재하지 않는 예약일 경우
![image](https://github.com/user-attachments/assets/e68032f1-2155-4a1f-b50c-10b57488d56f)

## To Reviewers

- 궁금한 점이나 의견 있으시면 리뷰 부탁드립니다!

2024-09-08 11:32 UTC, muncool39 requested changes
확인했습니다. 수고하셨습니다! 👍
코멘트 남겼습니다! 😃

2024-09-08 11:32 UTC, muncool39 commented on src/main/java/com/openbook/openbook/global/exception/ErrorCode.java
> +    ALREADY_RESERVED_SERVICE(HttpStatus.CONFLICT, "예약 가능한 시간이 아닙니다."),
메세지 부분이 "이미 예약된 날짜(또는 시간) 입니다." 등으로 변경되야 될 것 같아요!

2024-09-08 11:32 UTC, muncool39 commented on src/main/java/com/openbook/openbook/booth/service/common/CommonReservationService.java
> +    }
BoothReservationDetailService 에서 처리하는 유효성 검사를 해당 클래스에서 처리하는 것을 어떨까요?

2024-09-08 11:32 UTC, muncool39 commented on src/main/java/com/openbook/openbook/booth/controller/UserBoothController.java
> +    @PutMapping("/reserve/{detail_id}")
갑자기 생각난 건데 리소스의 부분적인 부분(상태 값)만 바꾸기 때문에 PATCH 로 요청을 보내는 것이 맞을 것 같다는 생각이 드네요. 이전에 PUT으로 썼던 부분도 생각해보고 PATCH로 고쳐도 될 것 같다는 생각이 들었습니다!😃

2024-09-08 12:32 UTC, gitseoyeon commented on src/main/java/com/openbook/openbook/booth/service/common/CommonReservationService.java
> +    }
그럼 commonReservationService에는 setUserToReservation 을 호출하는 코드만 남겨두면 될까요?!

2024-09-08 12:53 UTC, gitseoyeon commented on src/main/java/com/openbook/openbook/booth/controller/UserBoothController.java
> +    @PutMapping("/reserve/{detail_id}")
앗 그러네요!! patch의 존재를 잠시 잊고 있었습니다 ㅎ 수정해서 다시 올려보도록하겠습니다!

2024-09-08 13:02 UTC, gitseoyeon commented
말씀하신 의견반영해서 수정작업 완료했습니다 !!

2024-09-09 00:28 UTC, muncool39 reviewed
확인했습니다! 😃
추가로 생각난 것은 유저가 예약하는 시간이 그 예약정보(boothReservationDetail) 보다 이후면 오류가 반환되도록 하는 것은 어떨까요?

2024-09-09 00:28 UTC, muncool39 commented on src/main/java/com/openbook/openbook/booth/service/common/CommonReservationService.java
> +    }
앗 전에 리뷰 남긴
BoothReservationDetailService 에서 처리하는 유효성 검사를 해당 클래스에서 처리하는 것을 어떨까요?
↑ 뜻이 이 CommonReservationService 클래스에서 유효성 검사를 하면 좋을 것 같다는 의미였습니다!

2024-09-10 03:08 UTC, gitseoyeon commented on src/main/java/com/openbook/openbook/booth/service/common/CommonReservationService.java
> +    }
앗 제가 이해를 잘못했네요!! 다시 수정해서 올려보겠습니다!! 😅

2024-09-10 03:19 UTC, gitseoyeon commented on src/main/java/com/openbook/openbook/booth/service/common/CommonReservationService.java
> +    }
그러면 getReservationDetail 이 메서드를 CommonReservationService 여기로 옮겨보자는 의견이신가요?!

2024-09-10 03:37 UTC, gitseoyeon commented
유효성 검사 부분 위치 조정햇습니다!! 😊

2024-09-10 10:33 UTC, gitseoyeon commented
- 의견 주신 사용자의 현재 시간이 예약하려는 시간 이후의 시간일 경우의 오류 처리를 추가했습니다!
<img width="839" alt="image" src="https://github.com/user-attachments/assets/fde98bcb-757b-46dc-aee1-47fe87696bf7">

2024-09-10 12:28 UTC, muncool39 approved these changes
확인했습니다! 수고하셨습니다👍

2024-09-10 13:10 UTC, merged