Fix: 이미 존재하는 예약의 동일 날짜를 가진 새 예약을 등록할 경우
Project-OpenBook/openbook-server pull request #227
Opened 2024-09-21 17:21 UTC by gitseoyeon

## Summary

- closed #226

## Key Changes

- reservation 객체를 저장하기 전 createReservationDetail 메소드에서 날짜 오류처리를 한 후 객체를 db에 저장하도록 했습니다.
- checkExistTime 메소드에서는 입력 받은 시간들중 이미 존재하는 시간이 있는 boothReservationDetail 객체 리스트를 조회해서 그 객체들 안에서 시간과 날짜가 모두 일치하는 detail 데이터가 존재할 경우 오류처리를 했습니다.
## Testing

- 같은 날짜의 다른 시간 데이터를 저장할 경우 저장이 되는 것을 확인했습니다.
- 같은 날짜에 같은 시간의 데이터를 요청할 경우 오류 처리가 됩니다.
## To Reviewers

- 구현하면서 생각이 든건데 이렇게 되더라도 만약 등록하고자 하는 완전히 다른 예약 서비스를 새로 등록하고자 할 때 이전에 등록한 예약 서비스의 시간과 날짜가 완전히 같을 경우에는 오류처리가 되는 것은 동일 한 것 같아 고민이 되네요 ..! 
예를 들어, 어떠한 부스에 A 예약 서비스에 (9/10 [01:00, 02:00] , 9/11 [10:00, 12:00]) 으로 등록이 이미 되어 있고 새로 B 예약 서비스를 등록 할 때 날짜와 시간이 (9/09 [10:00, 11:00], 9/10 [01:00]) 이렇게 등록하고 싶을 경우 9/10 01:00 의 데이터가 겹치게 되어 오류가 나타나는 상황에 문제가 될 수 있겠네요!
혹시 이 부분에 대해 의견 말씀해주신다면 감사하겠습니다! 😊
- 추가로 의견이나 질문사항 있으시면 리뷰 남겨주세요!

2024-09-22 06:50 UTC, muncool39 reviewed
확인했습니다! 
주신 의견에 관련해서는 시간 디테일이 날짜의 하위에 들어가는 방식이 아닌 예약 서비스의 하위로 들어가게 하면 될 것 같습니다! 카테고리 처럼요
지금은 날짜를 사용해 무조건 그 날짜에 맞게 매칭하고 있는데 수락된 예약 id의 하위로 넣을 경우 그 예약 서비스 안에서만 중복되는 시간이 있는지 확인하면 문제가 해결될 것 같습니다!

또 예약 서비스를 추가할 때는 같은 날짜 같은건 허용하고 예약서비스 이름 등에서 중복 체크를 하면 될 것 같네요.
또 신청 후 허가 받은 예약 서비스에 대해서만 시간을 추후에 추가할 수 있도록 하는 방법도 있을 것 같습니다!

위에서 작성한 내용을 정리하면 이런 느낌일 것 같습니다.
1. 예약 서비스 추가 신청 (같은 날짜는 허용, 서비스 이름 중복 체크)
2. 승인 될 경우 해당 서비스의 아래에 시간 디테일 추가 (같은 예약 서비스에서 시간 중복 체크)

이렇게 되면 동일한 날짜와 시간인 경우도 상위 서비스 (연결된 서비스)가 다르다면 허용되도록 될 것 같습니다.

2024-09-22 12:43 UTC, gitseoyeon commented
자세한 설명 감사합니다 !! 👍🏻
'수락된 예약 id의 하위', '신청 후 허가 받은 예약 서비스' 라는 말이 부스 예약을 사용할 일반 유저가 예약을 신청했을 경우를 말씀하시는 건가요? 현재 저희 예약 등록 기능은 따로 예약 등록을 할 때 신청을 하는 것이 아닌, 등록을 하는대로 바로 등록이 되는 시스템이라 제가 이해한 경우가 맞는지 다시 확인 차 질문 드리고 싶었습니다!

2024-09-22 13:18 UTC, muncool39 commented
아 그 부분은 최근에 구현하신 사용자가 신청을 하고 허가를 받는 내용과 헷갈렸습니다! 죄송합니다😅

2024-09-22 15:00 UTC, gitseoyeon commented
의견 내주셔서 감사합니다!
우선 원래 요청한 날짜와 시간 둘 다 존재하는지 판단했던 부분을 날짜가 아닌 예약명으로 판단하는 걸로 구현했습니다.
그렇게 되면 다른 예약 서비스여도 날짜와 시간이 같은 경우가 등록이 될 것 같네요!
의견 주신 카테고리처럼 예약 서비스의 하위에 디테일 정보를 넣는 것은 추후 제가 더 고민해보고 구현해보도록 하겠습니다!

2024-09-23 01:49 UTC, muncool39 requested changes
확인했습니다! 궁금한 점 등 코멘트 작성했습니다! 😃
예약 디테일에 관련해서, 이미 엔티티 자체가 예약 서비스의 하위에 들어가 있기 때문에 구현 시에도 자연스럽게 그렇게 구현된다고 생각합니다! 그래서 말씀하신 "카테고리처럼 예약 서비스의 하위에 디테일 정보를 넣는 것" 은 어떻게 보면 지금 하고 있는 것이라고 생각합니다 애초에 예약이 없으면 디테일 생성이 안되니까요 🙂 그 점을 생각해서 구현하면 더 편하실 것 같습니다!

2024-09-23 01:49 UTC, muncool39 commented on src/main/java/com/openbook/openbook/repository/booth/BoothReservationDetailRepository.java
> +    boolean existsByLinkedReservation_NameAndTime(String name, String time);
그런데 이 경우 다른 부스의 예약 서비스 명이 중복될 경우의 처리는 잘 이루어지는 걸까요?
연결된 예약의 id 등 pk를 통해 조회해야 정확하게 이루어 질 것 같습니다. 🙂

2024-09-23 01:49 UTC, muncool39 commented on src/main/java/com/openbook/openbook/service/booth/BoothReservationService.java
>      public void addReservation(Long userId, ReserveRegistrationRequest request, Long boothId) {
지금 해당 메서드에서는 무조건 예약을 생성하는 걸로 이해하면 될까요?

2024-09-23 01:49 UTC, muncool39 commented on src/main/java/com/openbook/openbook/service/booth/BoothReservationDetailService.java
> +                    }
이 경우 reservation 안에 time이 존재하는지 판단하면 될 것 같습니다! 굳이 date 와 name 등의 속성을 빼지 않구요
위에도 작성했지만 엔티티 자체 또는 id로 조회해야 정확할 것 같습니다

2024-09-23 01:49 UTC, muncool39 commented on src/main/java/com/openbook/openbook/repository/booth/BoothReservationDetailRepository.java
> +    boolean existsByTime(String date);
매개변수명을 date로 하신 이유가 따로 있으실까요?

2024-09-23 01:49 UTC, muncool39 commented on src/main/java/com/openbook/openbook/service/booth/BoothReservationDetailService.java
> +    private void checkExistDetail(List<String> times, BoothReservation reservation){
혹시 해당 메서드가 어떤 동작을 하는지 알 수 있을까요?

2024-09-23 01:52 UTC, muncool39 commented
날짜와 이름의 중복 체크는 예약 디테일 서비스가 아닌 예약 서비스에서 진행하면 될 것 같습니다 ! 🙂

2024-09-23 02:02 UTC, muncool39 commented
추가적으로 궁금한 것은 해당 api 로 예약, 예약 디테일 추가를 한번에 하고 따로 디테일 추가 api 는 없다고 생각하면 되는 걸까요?
api를 분리하는지 아닌지에 따라 구현 로직에 차이가 있을 것 같아서 질문드립니다 😃
구현 시에도 예약 추가/ 예약 디테일 추가를 분리해서 생각하면 덜 헷갈리실 것 같아요!
개인적으로는 그냥 프론트랑 얘기해서 두 api 나눠도 좋을 것 같습니다

2024-09-23 06:09 UTC, gitseoyeon commented on src/main/java/com/openbook/openbook/repository/booth/BoothReservationDetailRepository.java
> +    boolean existsByLinkedReservation_NameAndTime(String name, String time);
테스트 했을 때는 같은 예약명에 같은 시간의 예약을 등록할 경우 에러 처리가 나는 것을 확인 바가 있습니다!
몰론 예약명을 다르게하고 시간을 같게 한 경우에는 등록이 잘 되고 있습니다.
다음은 테스트 했을때의 실행결과입니다.
- 같은 이름과 시간대의 예약을 추가했을 경우 (기존에 있던 예약 데이터: 예약명(예약명) / 시간 (13:00))
![image](https://github.com/user-attachments/assets/98b3aac2-40a5-42c0-9349-4b6d4122f2af)
![image](https://github.com/user-attachments/assets/198ad27f-38e1-4f9a-8584-61ef96e5b53f)
![image](https://github.com/user-attachments/assets/696eabfb-bd47-4994-8790-22401fa174f6)
- 같은 시간대지만 다른 예약명으로 등록했을 경우 (예약명: 다른 예약명 / 시간 13:00)
![image](https://github.com/user-attachments/assets/1dd721e4-b34e-4ece-8881-4f28e6f47ff2)

2024-09-23 06:14 UTC, muncool39 commented on src/main/java/com/openbook/openbook/repository/booth/BoothReservationDetailRepository.java
> +    boolean existsByLinkedReservation_NameAndTime(String name, String time);
오류 반환 확인했습니다!  그런데 다른 부스에서 같은 예약 서비스 명을 사용할 경우도 있을 것 같아서
이 경우에는 오류를 반환하지 않아야 될 것 같아서 해당 처리가 되는지 여쭙고 싶었어요!

2024-09-23 11:51 UTC, gitseoyeon commented on src/main/java/com/openbook/openbook/repository/booth/BoothReservationDetailRepository.java
> +    boolean existsByLinkedReservation_NameAndTime(String name, String time);
아 다른 부스일 경우에도 서비스명이 같을 경우를 생각 못했네요!! 제가 질문을 잘못 이해한것 같습니다 😅

2024-09-23 11:55 UTC, gitseoyeon commented on src/main/java/com/openbook/openbook/service/booth/BoothReservationService.java
>      public void addReservation(Long userId, ReserveRegistrationRequest request, Long boothId) {
이미 있는 예약에 따로 시간을 추가하는 경우는 API를 따로 개발하는 방향으로 생각하고 개발하긴 했습니다!
하나의 API로 새 예약 등록 및 추가를 진행하는 방향이 더 나을까요?!

2024-09-23 12:18 UTC, gitseoyeon commented on src/main/java/com/openbook/openbook/repository/booth/BoothReservationDetailRepository.java
> +    boolean existsByTime(String date);
이부분은 제가 오타를 낸 듯합니다!! 수정하겠습니다!

2024-09-23 12:20 UTC, gitseoyeon commented on src/main/java/com/openbook/openbook/service/booth/BoothReservationDetailService.java
> +    private void checkExistDetail(List<String> times, BoothReservation reservation){
받아온 시간들중 이미 같은 시간대로 저장된 예약 상세 객체들을 불러와서 그 객체들 중에 이름과 날짜가 같은 객체가 존재한다면 오류를 반환하는 메소드 입니다!

2024-09-23 12:28 UTC, gitseoyeon commented
앞서 잠깐 언급한 바와 같이 현재 구현한 방향은 새 예약을 등록하는 API와 이미 있던 예약에 시간만 추가하는 API를 따로 개발할 예정으로 생각했습니다. 이 사항에 있어서는 이번 회의때 한번 이야기 나눠보도록 하겠습니다!

2024-09-23 12:31 UTC, gitseoyeon commented
> 날짜와 이름의 중복 체크는 예약 디테일 서비스가 아닌 예약 서비스에서 진행해야 될 것 같습니다 ! 🙂 다시 보니까 예약 서비스에서 진행해야 될 내용이 예약 디테일의 시간 중복체크에 포함되어 있는 것 같아요 ! 예약에 관한 처리는 예외 서비스에서 하고 디테일 서비스로 넘어가면 될 것 같습니다 !

날짜와 이름의 중복 체크는 원래 완전히 같은 예약 서비스가 존재하는지 판별하기 위해 작성한 부분인데, 위에 말씀하신 것처럼 날짜와 이름을 따로 빼지 않고 진행한다면 아예 제거하는게 좋을 듯 싶습니다 🙂

2024-09-23 15:04 UTC, gitseoyeon commented
현재 문제가 본인 부스에서 등록하려는 예약 내용이 중복되지 않더라도, 다른 부스와 정보가 완전히 겹치면 중복으로 체크되는 문제를 방지하기 위해 등록되어있는 예약 정보가 본인 부스가 업로드한 것인지 판단하는 로직이 필요한 부분입니다.

위에서 말씀해주신 부분을 이해한 바로는 만들어진 Reservation 객체의 id를 이용해서 ReservationDetail 안에서 연결된 Reservation의 id와 비교후 조회를 한 다음 그 조회한 데이터를 이용해서 time이 존재하는 방향으로 말씀하신 게 아닌가 싶은데요!

여기서 PK를 비교해보았자 모든 예약 정보 내용들은 전부 PK가 다른데, 어느 부분에서 PK를 사용해 판별하는 건지 이해가 어렵습니다.
혹시 PK에 연결된 linkedBooth와 비교해서 판별하는건 어떨까요?

2024-09-23 16:02 UTC, gitseoyeon commented
우선 수정 작업을 마쳤습니다!
앞서 말씀해주신 것처럼 같은 데이터의 다른 부스가 등록 될 때 중복 처리가 되는 문제를 해결하기 위해서 다음과 같은 로직을 구현하였습니다.

```
1. getBoothReservations 메소드를 이용해서 부스 아이디와 일치하는 boothReservation 리스트를 조회합니다.
2. 조회한 리스트 안에서 예약 명, 예약 날짜, 예약 시간이 온전히 일치하는지 판별하고 일치할 경우 에러를 반환 합니다.
```
의견 주신 사항에 대해 깊게 고민해보았지만 제가 개발하는데 있어 이해가 부족해 온전히 구현하지는 못했습니다. 🥲
제가 구현한 사항은 지금 당장 등록하는데 문제가 없는 것 같지만 시간 복잡성을 고려하면 그렇게 효율적이지 못하다는 생각도 드네요..!

앞으로 더 공부해보고 고민해보도록 하겠습니다!!
제가 수정한 사항에 대해서도 의견이나 질문 사항 있으시면 코멘트 남겨주세요 😊

2024-09-24 05:21 UTC, muncool39 commented
> 위에서 말씀해주신 부분을 이해한 바로는 만들어진 Reservation 객체의 id를 이용해서 ReservationDetail 안에서 연결된 Reservation의 id와 비교후 조회를 한 다음 그 조회한 데이터를 이용해서 time이 존재하는 방향으로 말씀하신 게 아닌가 싶은데요!
> 
> 여기서 PK를 비교해보았자 모든 예약 정보 내용들은 전부 PK가 다른데, 어느 부분에서 PK를 사용해 판별하는 건지 이해가 어렵습니다.

이 부분은 To Reviewers 부분에서  말씀하신 

> 어떠한 부스에 A 예약 서비스에 (9/10 [01:00, 02:00] , 9/11 [10:00, 12:00]) 으로 등록이 이미 되어 있고 새로 B 예약 서비스를 등록 할 때 날짜와 시간이 (9/09 [10:00, 11:00], 9/10 [01:00]) 이렇게 등록하고 싶을 경우 9/10 01:00 의 데이터가 겹치게 되어 오류가 나타나는 상황

에 대해 다시 얘기하면서 설명드리자면
- 처음 예약을 추가할 때 이미 해당 부스의 예약에 9/10 date가 있는 경우, name을 체크해 해당 날짜 중복을 가능하게 한다

이렇게 할 경우 9/10, 9/10 으로 날짜가 같아도 이름이 다르면 "부스 예약" 엔티티는 저장되겠죠! 이때는 연결된 부스 id를 통해 같은 부스 안에 해당 날짜와 이름을 가진 정보가 있는지 확인하면 될 것 같습니다. 그래서 이때는 연결된 부스의 pk를 사용하면 되겠죠

리뷰 작성한 "Reservation의 id" 로 조회하는 부분은 디테일에서의 중복 처리를 말씀드린건데요
9/10 날짜 중복 처리는 위 과정으로 끝이고, 01:00 의 시간 중복 처리에 대한 내용입니다! 자세히 설명드리면

만약 B 서비스의 9/10 의 안에 01:00 을 추가하고자 할 때, A예약 서비스에 9/10 날짜에 이미 01:00 이 있기 때문에
전처럼 "해당 날짜 안에 시간이 있는지" 만 비교하면 제대로 추가되지 않아서,
바꾸신 것처럼 date와 서비스 name 이 일치하는 데이터 안에서 시간을 찾게 하면 B 서비스에 생성할 수 있겠죠!

그런데 이렇게 할 경우 다른 부스에서 date와 name을 동일하게 사용하는 예약이 있을 경우의 처리가 제대로 이루어 지지 않습니다.

이 때 date와 name 두 정보를 찾아서 시간이 있는지 체크하는 방법이 아닌 연결된 예약 엔티티의 pk를 사용하자는 의미였습니다!
예약 엔티티 안에서만 일치하는 시간이 있는지 조회하면 date, name, 연결된 부스 세가지 조건을 다 처리할 수 있으니까요

만약 B서비스의 날짜 9/10 엔티티의 pk(id)가 2라면
- 예약 서비스 이름이 B고 날짜가 9/10 이고 부스id가 oo인 데이터에 시간 정보가 있는지 확인 
- 연결된 예약 서비스의 id가 2인 엔티티에 동일한 시간이 있는지 확인

후자를 사용하면 좋지 않을까 하는 의견이였습니다! 🙂 성능면에서도 빠르지 않을까 하네요
 

> 여기서 PK를 비교해보았자 모든 예약 정보 내용들은 전부 PK가 다른데

각 예약 서비스, 예약 디테일의 pk는 다르겠지만 한 예약 서비스의 하위에 들어가는 예약 디테일들은 "연결된 예약 서비스"가 같은 pk를 가리키기 때문에 한 예약 서비스 (날짜) 안의 디테일(시간) 의 중복 처리를 하고자 할 때 사용하자는 이야기 였습니다!

정리하면
- 날짜 중복 확인 시 연결된 부스 안에서만 확인 (연결된 부스 id 활용)
- 시간 중복 확인 시 연결된 예약 안에서만 확인 (연결된 예약 id 활용)

그리고 두 과정을 굳이 한 메서드에서 처리하지 않고 날짜 중복 확인은 예약 클래스에서,
날짜 확인 통과 시, 디테일 서비스로 예약 정보 전달해 시간 중복 확인은 예약 디테일 서비스에서 하면 될 것 같습니다.
두 과정을 나누면 덜 복잡하실 것 같습니다. 🙂

2024-09-24 05:24 UTC, muncool39 commented
그리고 위 코멘트 작성하면서 궁금한 점도 생겼는데 예약 엔티티를 보면

![image](https://github.com/user-attachments/assets/3a3ca774-60ee-4316-b65d-6e17fe826f2a)
한 예약 서비스가 한 date 를 가지는 것 같은데
"A 예약 서비스에 (9/10 [01:00, 02:00] , 9/11 [10:00, 12:00]) 으로 등록" 처럼 두 날짜를 한번에 묶는 방법이 있을까요?
name을 같게 사용하는 걸로 묶는 걸로 생각하면 될까요?!

2024-09-24 05:38 UTC, muncool39 reviewed
코멘트 작성했습니다! 수정 고생 많으십니다 😥
혹시 이해 안되는 점이나 의견 있으시면 말씀해주세요!

2024-09-24 05:38 UTC, muncool39 commented on src/main/java/com/openbook/openbook/service/booth/BoothReservationService.java
>      public void addReservation(Long userId, ReserveRegistrationRequest request, Long boothId) {
저도 나누는 것이 더 좋다고 생각합니다 ! 👍

2024-09-24 12:28 UTC, gitseoyeon commented
> 그리고 위 코멘트 작성하면서 궁금한 점도 생겼는데 예약 엔티티를 보면
> 
> ![image](https://private-user-images.githubusercontent.com/105481797/370129976-3a3ca774-60ee-4316-b65d-6e17fe826f2a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjcxNzU5NjUsIm5iZiI6MTcyNzE3NTY2NSwicGF0aCI6Ii8xMDU0ODE3OTcvMzcwMTI5OTc2LTNhM2NhNzc0LTYwZWUtNDMxNi1iNjVkLTZlMTdmZTgyNmYyYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkyNFQxMTAxMDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01ZWY3ODY2YWQ2ODhmNTMzZjYzNDVkMTI3MDA2OTNmZTQ0NmRjMTIwNWJjMjhlZGVjMDBkMjUzMGZiMTU4YmZkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.-Brwh2-_6aywZ3CZtk04tXMIcOByfcj1dEu9Ei3Sg8o) 한 예약 서비스가 한 date 를 가지는 것 같은데 "A 예약 서비스에 (9/10 [01:00, 02:00] , 9/11 [10:00, 12:00]) 으로 등록" 처럼 두 날짜를 한번에 묶는 방법이 있을까요? name을 같게 사용하는 걸로 묶는 걸로 생각하면 될까요?!

이분에 있어서는 저도 고민을 해보았었는데요! 현재는 저렇게 등록해야할 경우 API를 두번 호출하게 하고 있습니다. name을 같게 사용하는 걸로 묶는 다는게 어떤 느낌인지 말씀해주시면 감사하겠습니다!!

2024-09-24 12:51 UTC, gitseoyeon commented
상세한 설명 정말정말 감사합니다 🥹 덕분에 이해가 훨씬 잘 됐습니다!! 👍🏻
제가 맞게 이해한 건지는 모르겠지만 우선 boothReservationService에서 연결된 boothId 와 같은 예약 데이터 중에서 날짜와 이름이 같은 데이터가 있는지 판별하는 checkDuplicateDates 메소드를 구현했습니다.
그 후에 BoothReservation 객체를 만들고 BoothReservationDetailService 로 들어가서 checkAvailableTime 이라는 입력한 시간이 유효한 시간인지 판별하는 메소드 과정을 거칩니다.
여기서 말씀하신 연결된 예약 id 를 이용해서 동일 시간 판별하는 과정은 

> 연결된 예약 서비스의 id가 2인 엔티티에 동일한 시간이 있는지 확인

이때 예약 서비스는 boothReservationService 에서 생성이 되기 때문에 id가 생기겠지만, boothReservationDetail 같은 경우는 아직 에러 판별하는 과정이기 때문에 db에 시간 정보(boothReservationDetail)가 저장되지 않습니다. 즉 id가 2인 엔티티에 시간 정보가 아직 저장이 안됐기때문에 시간정보를 조회할 수가 없어 NullPointerException 에러가 발생합니다. 

코멘트에 작성하신 것처럼 새로 작성한 엔티티이기 때문에 중복 시간이 없을 것 같아 추후 예약 시간을 추가하는 과정에서 시간 중복 판별을 해볼까합니다! 🙂

지금까지 구현한 사항은 테스트해보았을 때 문제가 되는점은 없어보여 커밋 올려보았습니다. 혹시 제가 이해를 잘못한 부분이 있거나 다른 의견 사항 있으시면 말씀해주세요!

2024-09-24 15:13 UTC, muncool39 reviewed
변경 확인했습니다! 수고많으셨습니다! 👍
추가적으로 코멘트 남겼습니다! 😊


> 이때 예약 서비스는 boothReservationService 에서 생성이 되기 때문에 id가 생기겠지만, boothReservationDetail 같은 경우는 아직 에러 판별하는 과정이기 때문에 db에 시간 정보(boothReservationDetail)가 저장되지 않습니다. 즉 id가 2인 엔티티에 시간 정보가 아직 저장이 안됐기때문에 시간정보를 조회할 수가 없어 NullPointerException 에러가 발생합니다.

이 부분에 대해서는 existsBy 를 사용하면 에러 없이 데이터의 유무를 확인할 수 있을 것 같지만, 말씀하신 것처럼 추후 예약 시간을 추가하는 과정에서 구현해도 충분히 괜찮다고 생각합니다! 👍

> name을 같게 사용하는 걸로 묶는 다는게 어떤 느낌인지 말씀해주시면 감사하겠습니다!!

이 부분에 대해선, 한 부스의 예약 엔티티가  name, date 등을 가지는데
서비스 명이 A라고 하면, name을 A로 지을 텐데 name이 A인

2024-09-24 15:13 UTC, muncool39 commented on src/main/java/com/openbook/openbook/service/booth/BoothReservationService.java
> +        }
이 부분은 위에서 작성하신 existsByDateAndName 처럼 exists 쿼리를 사용해서 간단하게 바꿀 수 있을 것 같습니다! 연결된 부스 id, date, name 세가지 조건을 활용해서 exists 쿼리를 작성하면 될 것 같네요. 😃

만약에 쿼리메서드 명이 너무 길어진다면 limit 1을 사용한 count 쿼리문을 작성하면 될 것 같습니다!
limit 1 사용에 관한 참고용 링크입니다! https://jojoldu.tistory.com/516

개인적으로는 그냥 exists 를 사용해도 괜찮을 것 같네요!

2024-09-24 15:13 UTC, muncool39 commented on src/main/java/com/openbook/openbook/service/booth/BoothReservationDetailService.java
> +        }
갑자기 생각난 것인데 List 안에 중복 데이터가 있는지도 확인하는 건 어떨까요?
TagUtil 에서 구현한 getValidTagsOrException 메서드을 참고해서 구현해도 좋을 것 같네요!

2024-09-25 01:05 UTC, gitseoyeon commented
말씀해주신 사항에 대해 수정작업을 했습니다!

> 이 부분에 대해서는
한 부스의 예약 엔티티의 정보에 서비스명, 가격 등 정보가 들어갈텐데 예약 엔티티에서 date 를 하나만 가지기 때문에
서비스 명 A에 여러 date를 넣고자 할 경우, date를 생성할 때마다 name을 A로 보내는 식으로 같은 서비스로 묶는 건지 궁금했습니다! 🙂

이 부분은 위에 말씀드린 것처럼 name을 동일하게 api를  여러번 호출하게 된다면 같은 name으로 다른 데이터들이 저장되기 때문에 말씀하신 내용이 맞을 것 같습니다!

2024-09-25 05:50 UTC, muncool39 reviewed
변경 확인했습니다! 수고하셨습니다 👍 한 가지 코멘트 남겼습니다!

2024-09-25 05:50 UTC, muncool39 commented on src/main/java/com/openbook/openbook/service/booth/BoothReservationDetailService.java
> +                });
두 유효성 확인 과정을 분리할 경우 list 를 두 번 확인하게 되는데
두 과정을 한번의 forEach 에서 처리하는 것은 어떨까요?

2024-09-25 08:10 UTC, gitseoyeon commented on src/main/java/com/openbook/openbook/service/booth/BoothReservationDetailService.java
> +                });
좋은 방법인 것 같습니다! 시도해보고 다시 커밋 올리겠습니다~

2024-09-26 00:06 UTC, gitseoyeon commented
말씀하신 예약 가능 시간 판별하는 두개의 메소드를 하나의 forEach 문에서 해결하도록 병합했습니다! 확인 부탁드립니다~

2024-09-26 00:20 UTC, muncool39 approved these changes
확인했습니다! 수고하셨어요~ 😃

같은 서비스를 묶는 것에 대해서는 서비스 정보 테이블을 분리해야 된다고 생각하는데 이 건에 대해서는 추후 말씀드리겠습니다~

2024-09-26 00:28 UTC, merged