Feat: 부스 등록 기능 API
Project-OpenBook/openbook-server pull request #23
Opened 2024-05-22 15:23 UTC by gitseoyeon

## Summary

- closed #12 
POST 형식으로 부스의 기본정보를 입력해 저장하는 API 입니다.
## Key Changes

- UserBoothController, BoothService, BoothLoactionService, BoothRepository, BoothLoactionRepository를 만들어서 부스 등록에 필요한 데이터를 db에 저장했습니다.
- BoothRegistrationRequest 이라는 record를 생성해서 클라이언트로부터 정보를 입력 받아 전달하도록 했습니다.
- 행사 등록시 먼저 구현하셨던 s3 관련 메서드를 동일하게 사용해서 부스 등록시 저장할 사진을 s3에 저장하도록 했습니다.
- datePeriodCheck() 메서드와 if문을 사용해서 오류 시 메세지를 전달하도록 구현하였습니다.
## Testing

- 부스 등록을 할 경우
![image](https://github.com/Project-OpenBook/openbook-server/assets/126096318/cb227e84-d010-43a9-90ac-8ce0179501ea)

- 오픈 시간과 마감 시간을 잘못 기입했을 경우
![image](https://github.com/Project-OpenBook/openbook-server/assets/126096318/677d8d35-3fb0-432e-8c0c-c3bd3858c4a7)

- 이미 예약된 부스 자리에 등록 할 경우
![image](https://github.com/Project-OpenBook/openbook-server/assets/126096318/223c65fe-e8d9-4639-ba53-87694d787bc9)

## To Reviewers

- BoothService에서 getEventOrException 메서드를 이용해서 행사 객체를 찾거나 오류를 리턴하는 것을 구현했는데, BoothLocationService의 경우에는 따로 오류를 처리하는 메서드를 구현하지 않고 바로 boothLocation을 구하도록 했습니다. 피그마를 보니 부스 등록 전에 이미 행사를 선택했기 때문에 행사 정보는 자동으로 기입되도록 되어있어서 BoothService에서 이벤트 객체를 굳이 getEventOrException 를 이용해서 찾아야 할 지 고민이 되었습니다. 그냥 BoothLocationService처럼 바로 event를 구할 지 지금 처럼 할 지 좋은 의견 있으시면 말씀해주세요!
- 처음에 controller, dto, service  등등 메서드나 파일 명 앞에 create를 붙여서 만들었었는데, 행사와 통일성 있게 이름이 지어지면 좋을 것 같아서 create 대신 UserBoothController로 변경하거나 메서드명과 record명에 Registration를 붙여 변경했습니다!
- 부스 등록할 떄, 상품과 서비스 예약 정보까지 등록을 구현 하기 위해 우선 엔터티와 테이블만 만들어 두었습니다! 나중에 구현 할 때 사용하면 될 거같습니다.
- 부스 시간을 등록 할 때 LoacalDateTime 특성상 시간 뿐만 아니라 날짜까지 같이 써야하는 문제가 있습니다. 현재는 일단 임의로 날짜까지 넣어서 db에 저장했는데, 혹시 시간만 잘라서 db에 전달하는 방법을 아신다면 공유 부탁드립니다 ㅎㅎ

2024-05-23 08:25 UTC, muncool39 requested changes
수고하셨습니다 !
일단 부스 생성 기능 개발이 우선이라, pr에 포함된 부스 상품이나 부스 예약 등에 대해서는 리뷰하지 않았습니다. 이후 제대로 엔티티를 확인하고 수정하는 과정도 있으면 좋을 것 같습니다. 😃
To Reviewers 관련해서
- 화면에서는 바로 연결되지만, 저희가 postman으로 보내며 테스트하는 경우도 있으니 확인하는 과정은 있어도 좋을 것 같습니다 !
- LoacalDateTime 관련해서는 시간 request 를 string type으로 받은 후, db에 저장할 땐 행사의 날짜를 가져오고 String 으로 받은 시간을 합쳐 저장하는 방법이 생각났습니다. db 자체의 포멧을 시간만 저장하도록 바꾸진 않아도 될 것 같은데, 만약 바꾼다면 아예 type을 varchar 로 바꾸는 방법이 있을 것 같습니다.

리뷰하면서 생각난 건, 현재 배치도와 구역이 모두 행사쪽에 있는데, 부스와도 연관이 되다 보니 해당 배치도를 따로 패키지로 분리하는 건 어떨까 생각이 들었습니다. 해당 내용 관련해서도 함께 생각해보면 좋을 것 같습니다 !

2024-05-23 08:25 UTC, muncool39 commented on settings.gradle
> +rootProject.name = 'openbook'
이 부분은 혹시 따로 의미가 있을까요? 
아니면 제외시켜도 좋을 것 같습니다 !

2024-05-23 08:25 UTC, muncool39 commented on src/main/java/com/openbook/openbook/booth/service/BoothLocationService.java
> +        }
해당 내용 관련해서 해당 메서드는 부스구역테이블에 생성 후 상태를 WAITING으로 바꾸고 있는데
저희가 구상한 부스 등록-승인 로직이
1. 자리를 포함해 부스를 신청한다
2. 해당 자리 상태는 WAITING 로 바뀐다
3. 부스가 승인이 되면 자리 상태가 COMPLETE 가 된다
4. 위와 함께 부스 구역 테이블에 내용을 저장한다

![image](https://github.com/Project-OpenBook/openbook-server/assets/105481797/44e2aebe-5b9f-4965-8673-dd19a481104c)
그래서 WAITING 도 선택 불가긴 하지만, 승인 전까지는 정식으로 자리가 잡히는게 아니게 되는 것이라고 생각했습니다. 그래서 부스 구역에 미리 저장하지 않고, EventLayoutAreaStatus를 WAITING으로 바꾸는 내용만 사용하면 될 것 같습니다 !!
지울 필요는 없고 승인 구현 시 해당 메서드를 사용하면 좋을 것 같습니다..!!

2024-05-23 08:25 UTC, muncool39 commented on src/main/java/com/openbook/openbook/event/entity/EventLayoutArea.java
> +    public void updateStatusWaiting(){ this.status = EventLayoutAreaStatus.WAITING; }
상태가 변경되는 내용이 자주 사용될 것 같은데,
WAITING 으로 바꾸는 메서드가 아니라 입력받은 상태로 바꿀 수 있도록 하는 건 어떨까요?
ex
```java
public void updateStatus(EventLayoutAreaStatus status) {
   this.status = status;
}
```

2024-05-23 08:25 UTC, muncool39 commented on src/main/java/com/openbook/openbook/booth/dto/request/BoothRegistrationRequest.java
> +        @NotNull MultipartFile mainImageUrl,
request 에 들어오는건 url 이 아니라 파일이기 때문에 변수명에 Url을 제외하는건 어떨까요?

2024-05-23 08:25 UTC, muncool39 commented on src/main/java/com/openbook/openbook/booth/service/BoothService.java
> +        boothLocationService.createBoothLocation(booth, request.locations());
위에 리뷰한대로 해당 서비스는 승인 시 사용하고 상태를 부스 상태를 WAITING 으로 바꾸는 내용만 사용하면 될 것 같습니다 !
그리고 구역 상태를 확인하는게 부스 생성 전에 가능하니까 해당 자리가 EMPTY 인지 확인하는 과정을 생성보다 먼저 넣으면 어떨까요?

2024-05-23 08:25 UTC, muncool39 commented on src/main/java/com/openbook/openbook/booth/dto/request/BoothRegistrationRequest.java
> +        @NotNull String accountNumber
혹시 저희 계좌번호도 필수입력으로 하기로 했을까요? 
회의 때 필수 데이터인지도 말했는지 기억이 잘 안나는데 안적어도 되지 않을까 해서 여쭤봅니다!!

2024-05-23 08:32 UTC, gitseoyeon commented on settings.gradle
> +rootProject.name = 'openbook'
이 부분은 저도 왜인지는 모르겠으나 자동으로 추가 돼 있더라고요...? 우선 제거해보도록 하겠습니다!

2024-05-23 12:41 UTC, gitseoyeon commented on src/main/java/com/openbook/openbook/booth/service/BoothLocationService.java
> +        }
아 저는 로직을 신청하면 무조건 저장이 되는걸로 생각하고 있었네요! 말씀하신것처럼 우선 신청하면 상태만 바뀌고 추후 승인 나면 저장하는게 맞는거같아요! 수정하겠습니다~~

2024-05-23 12:42 UTC, gitseoyeon commented on src/main/java/com/openbook/openbook/booth/dto/request/BoothRegistrationRequest.java
> +        @NotNull MultipartFile mainImageUrl,
앗 넵 mainImage로 변경하겠습니다!!

2024-05-23 12:47 UTC, gitseoyeon commented on src/main/java/com/openbook/openbook/booth/service/BoothService.java
> +        boothLocationService.createBoothLocation(booth, request.locations());
엇 이부분은 제가 구현 한 게 있었는데 실수로 지워진거같습니다! 다시 구현해서 올리겠습니다~

2024-05-23 12:48 UTC, gitseoyeon commented on src/main/java/com/openbook/openbook/booth/dto/request/BoothRegistrationRequest.java
> +        @NotNull String accountNumber
아 사실 필수로 입력하자는 말은 없었는데 제가 테스트하면서 오류가 나서 임의로 저렇게 설정했던 것같습니다! 제 기억상으로는 필수는 아니었던것 같습니다!

2024-05-23 17:19 UTC, muncool39 requested changes
변경사항 확인했습니다! 수고하셨습니다! 👍 추가로 리뷰한 내용만 반영하면 될 것 같습니다!
관계가 복잡하다보니 헷갈리는 부분이 많이 생길 것 같은데,
그럴때마다 같이 의견 나눠보면서 해결하면 좋을 것 같아요.☺

2024-05-23 17:19 UTC, muncool39 commented on settings.gradle
> -rootProject.name = 'openbook'
앗 이게 초기 설정에 있던 내용이라, 아예 코드를 없애기보단 변경사항에서 없애도 될 것 같습니다 !
dev에 포함될 부스 등록 커밋에 해당 내용이 포함되지 않도록 하면 좋을 것 같아요!

2024-05-23 17:19 UTC, muncool39 commented on src/main/java/com/openbook/openbook/event/entity/EventLayoutArea.java
> +    public void updateStatusWaiting(EventLayoutAreaStatus status){ this.status = status; }
waiting이 아닌 받은 status로 변경하기 때문에 메서드명도 변경하면 좋을 것 같습니다 !

2024-05-23 17:19 UTC, muncool39 commented on src/main/java/com/openbook/openbook/booth/service/BoothService.java
코드를 보면서 생각난건데, 시간 오류를 체크할 때
Event에서 현재 날짜가 행사의 부스 모집 기간에 해당하는지 확인하는 로직도 필요할 것 같습니다 ! 😭
boothRecruitmentStartDate < 현재 < boothRecruitmentEndDate 를 확인해야 할 것 같아요 !

2024-05-23 17:19 UTC, muncool39 commented on src/main/java/com/openbook/openbook/booth/service/BoothService.java
> +        boothLocationService.boothLocationApplication(request.locations());
해당 줄을 booth를 build하기 전에 위치하도록 하는건 어떨까요?
문제될 건 없고 단순 의견입니다!

2024-05-23 17:31 UTC, gitseoyeon commented on settings.gradle
> -rootProject.name = 'openbook'
앗! ㅋㅋㅋ 그렇군요 참고하겠습니다!

2024-05-23 17:32 UTC, gitseoyeon commented on src/main/java/com/openbook/openbook/event/entity/EventLayoutArea.java
> +    public void updateStatusWaiting(EventLayoutAreaStatus status){ this.status = status; }
변경하면서 수정했어야했는데 깜빡 한 것 같네요 후딱 수정하겠습니다! 😭

2024-05-23 17:40 UTC, gitseoyeon commented on src/main/java/com/openbook/openbook/booth/service/BoothService.java
헉 그러네요 LocalDate.now() 로 현재 시간 받아와서 사용하면 될까요?!

2024-05-23 17:43 UTC, gitseoyeon commented on src/main/java/com/openbook/openbook/booth/service/BoothService.java
> +        boothLocationService.boothLocationApplication(request.locations());
부스 신청 상태를 변경하고 부스 정보를 저장하는 흐름을 위해서 말씀하신 걸까요?! 그런거라면 시간 오류 체크와 빌드 사이에 두면 될까용??

2024-05-24 05:39 UTC, muncool39 approved these changes
변경사항 확인했습니다 ! 수고하셨습니다~👍

2024-05-24 06:19 UTC, merged