Feat: 부스 수정 API
Project-OpenBook/openbook-server pull request #248
Opened 2024-10-02 01:05 UTC by gitseoyeon

## Summary

- closed #238 
PATCH /booths/{booth_id}

## Key Changes

- 수정할 데이터를 담을 request 클래스를 추가했습니다.
- 앞서 행사 리뷰 수정과 유사하게 추가할 태그 tagToAdd와 tagToDelete 필드를 만들었고, 이를 통해 최대 개수(5) 를 넘는지 판별하게 됩니다.
## Testing

- 성공 시
<img width="1065" alt="image" src="https://github.com/user-attachments/assets/5d1fa0fb-4afc-43e1-a683-3fbb017c3e79">

- 최대 개수를 넘는 경우
<img width="1063" alt="image" src="https://github.com/user-attachments/assets/e10a9cc1-b8d7-439f-b1b2-10b38df7005c">

- 삭제하려는 태그 데이터가 해당 부스의 태그 데이터가 아닐 경우
<img width="1049" alt="image" src="https://github.com/user-attachments/assets/cfa0e704-88d0-49b5-95f6-b3d65e1092b5">

## To Reviewers

- 태그 데이터를 일부 삭제하고 싶을 경우 원래는 jpa에서 기본으로 제공해주는 delete 메소드를 사용했었는데, 데이터가 제거되지 않고 update문이 나가는 문제가 발생했었습니다. 알아보니 정확한 이유는 아니지만 영속성의 문제라고 보이는데 지금 생각한 방안으로는 delete 쿼리문을 직접 만들어서 사용하는 방법으로 우선 개발했습니다. 혹시 다른 좋은 방법 생각나시면 말씀해주세요 !
- 저번 공지 수정건을 보니 dto를 따로 하나 만들어서 구현하셨던데 이번에도 그런 방향으로 할 지 의견 부탁드립니다!
- 다른 의견이나 질문 있으시면 리뷰 남겨주세요! 😊

2024-10-02 18:43 UTC, muncool39 requested changes
확인했습니다! 👍
아마 제가 전에 구현했던 행사 리뷰 수정 부분을 참고하신 것 같은데 행사 공지사항 수정 pr(#247 )의 코멘트에서 말씀드렸듯이 그때 쉽게 Put 요청 방식으로 개발하느라 요청 값을 필수로 받고 구현했어서 Patch 요청 방식으로 할 경우엔 구현하는 방식이 달라질 것 같습니다! 
dto건에 대해서는 만드셔도 좋을 것 같아요! 😃

2024-10-02 18:43 UTC, muncool39 commented on src/main/java/com/openbook/openbook/api/booth/request/BoothModifyRequest.java
> +        @NotNull MultipartFile mainImage,
해당 값들을 필수로 한 이유가 따로 있으실까요? 
Patch 요청으로 구현한다면 수정할 값만 넘겨도 될 것 같습니다!

2024-10-02 18:43 UTC, muncool39 commented on src/main/java/com/openbook/openbook/service/booth/BoothService.java
> +                request.accountNumber(), request.accountBankName(), open, close);
Patch 요청 형식으로 수정을 할 경우 바뀐 값만 업데이트 하도록 구현하면 좋을 것 같습니다!

2024-10-02 18:43 UTC, muncool39 commented on src/main/java/com/openbook/openbook/api/booth/BoothController.java
> +                                        @Valid BoothModifyRequest request){
위에 작성한 내용과 같은 맥락으로 리소스 일부만 수정하는 patch 메서드이고, 현재 필요한 필수값이 따로 없을 것 같습니다! 그래서 안에 들어갈 값이 바뀌기 때문에 BoothModifyRequest안을 검증하는 Valid 대신 BoothModifyRequest가 반드시 있어야 된다는 의미로 NotNull을 사용하면 좋을 것 같네요!

2024-10-02 18:43 UTC, muncool39 commented on src/main/java/com/openbook/openbook/service/booth/BoothTagService.java
> +    }
줄바꿈을 조금 줄여보는 건 어떨까요?!

2024-10-03 11:22 UTC, gitseoyeon commented on src/main/java/com/openbook/openbook/api/booth/request/BoothModifyRequest.java
> +        @NotNull MultipartFile mainImage,
이부분은 제가 patch 방식이 아닌 put으로 처음에 구현하면서 수정을 못했네요!! 수정 하겠습니다!

2024-10-03 12:34 UTC, muncool39 approved these changes
변경 확인했습니다! 수고하셨습니다! 👍

2024-10-03 13:46 UTC, merged