Feat: 해당 행사에 대한 부스 등록 신청 목록 조회
Project-OpenBook/openbook-server pull request #32
Opened 2024-05-26 04:00 UTC by gitseoyeon

## Summary

- closed #24
- 행사 id에 따른 부스들의 신청 목록들을 조회하는 기능입니다.

## Key Changes

- 그 전 행사 신청 목록 api 와 유사하게 페이지당 10개의 데이터를 담도록 했습니다.
- evnetId를 파라미터 값으로 주어서 해당 파라미터 값에 맞는 신청 부스들이 조회됩니다.
- 기본 파라미터 값은 all로, 모든 상태의 부스들을 조회하고 그 외의 파라미터 값을 넣으면 그에 맞는 상태의 부스들이 조회됩니다.
## Testing

- 신청 부스 조회 했을 때
![image](https://github.com/Project-OpenBook/openbook-server/assets/126096318/0719f36b-6c88-4da4-a3a7-188a43c15012)
- 특정 상태(waiting, approved) 의 부스를 조회할 때
![image](https://github.com/Project-OpenBook/openbook-server/assets/126096318/1ec97cbb-0817-4820-93ee-de01496181da)
![image](https://github.com/Project-OpenBook/openbook-server/assets/126096318/a2533cbc-602b-42d8-8b91-ea1f2acfbe76)
## To Reviewers

- 이전에 회의할 때 아직 신청 대기중인 부스의 위치가 저장되지 않는다는 이슈로 일단 조회할 때 부스 위치까지 조회하는 것은 주석처리해서 올렸습니다. 추후 이슈가 해결되고 다시 개발하도록 하겠습니다!
- 이 외에도 오류 전달 메세지나 변수명 등등 수정사항 있다면 말씀해주세요~

2024-05-26 05:45 UTC, muncool39 requested changes
확인했습니다 ! 
부스 수정사항 관련해서는 해당 pr 도메인이 eventmanager고 수정해야 할 부분이 user 도메인이니 수정 사항 반영 이후, 해당 브런치에 머지해서 한번에 개발하는 방법도 있을 것 같네요! 편한 쪽으로 진행하면 좋을 것 같습니다 ! 👍

2024-05-26 05:45 UTC, muncool39 commented on src/main/java/com/openbook/openbook/eventmanager/EventManagerController.java
> +    @GetMapping("/eventManager/{eventId}/booths")
api 경로에 대소문자를 같이 포함하지 않는 방향으로 수정하면 좋을 것 같습니다 !
하나 의견을 제시해보면, "/events/{eventId}/managed/booths"로 작성하면 이후 이벤트 관리자가 배치도 등을 관리할 때도 "/events/{eventId}/managed/layout"으로 사용 가능해 확장성이 좋을 것 같아요!

2024-05-26 11:52 UTC, gitseoyeon commented on src/main/java/com/openbook/openbook/eventmanager/EventManagerController.java
> +    @GetMapping("/eventManager/{eventId}/booths")
오! 좋은 조언 감사합니다! 수정해보겠습니다~~

2024-05-29 00:21 UTC, gitseoyeon commented
+ 지난 부스 신청시 해당 행사의 신청 구역에 대한 정보 저장이 안되는 이슈를 해결하고 추후 저장된 위치 정보를 기반으로 신청 부스들의 목록을 조회할 때 부스의 위치까지 응답하게 구현하였습니다! 확인 부탁드립니다 😊

- status가 all일 경우 응답하는 데이터 예시
<img width="709" alt="image" src="https://github.com/Project-OpenBook/openbook-server/assets/126096318/c8449576-419d-4ea5-92db-aadd1a638ab9">

2024-05-29 01:11 UTC, muncool39 requested changes
확인했습니다 !
전체적으로 mange~ 라고 되어있는데 manage 가 좀 더 명확할 것 같다는 생각이 들었습니다! 아니면 mange라고 하신 이유가 따로 있으실까요?
추가로 생각난 것은, event id 를 통해 해당 기능을 사용하기 때문에 "자신이 생성한 이벤트 목록" 을 조회하는 기능도 필요할 것 같네요~ 해당 내용 관련해서는 따로 구현 진행하면 좋을 것 같습니다.

2024-05-29 01:11 UTC, muncool39 commented on src/main/java/com/openbook/openbook/eventmanager/dto/BoothMangeData.java
> +public record BoothMangeData(
혹시 Mange 는 무슨 의미일까요?

2024-05-29 01:11 UTC, muncool39 commented on src/main/java/com/openbook/openbook/eventmanager/dto/BoothMangeData.java
해당 객체로 변환할 때의 데이터 순서를 맞춰줘야 할 것 같아요 ~

![image](https://github.com/Project-OpenBook/openbook-server/assets/105481797/525146c9-de11-4aa1-ad15-b168cb17bec2)

2024-05-29 01:11 UTC, muncool39 commented on src/main/java/com/openbook/openbook/eventmanager/EventManagerService.java
> +            return booths.map(this::convertToBoothMangeData);
Page<Booth> 가져온 다음 매핑하는 방식이 아닌 가져올 때부터 매핑하는 방식을 사용하는건 어떻게 생각하실까요?

2024-05-29 01:11 UTC, muncool39 commented on src/main/java/com/openbook/openbook/eventmanager/dto/BoothLocationData.java
혹시 해당 객체 명을 BoothAreaData 등으로 바꾸는 건 어떻게 생각하실까요?
당시에 BoothLocation이라는 테이블이 있었어서 비슷하게 된 것 같은데,
이제 Area에서 자리 정보를 사용하고, 변환 시 사용하는 데이터도 eventLayoutArea의 데이터라서
해당 내용(Area사용)이 좀 더 알기 쉬우면 좋을 것 같다는 생각이 듭니다 !

2024-05-29 01:11 UTC, muncool39 commented on src/main/java/com/openbook/openbook/eventmanager/EventManagerService.java
> +            default -> throw new OpenBookException(HttpStatus.BAD_REQUEST, "잘못된 요청 값 입니다.");
저는 해당 메세지를 "요청 값이 잘못되었습니다." 라고 했는데
같은 유형의 오류니 메세지를 통일하는 건 어떻게 생각하시나요? 
어느 쪽이든 메세지를 같게 주는 것이 좋을 것 같습니다 !

2024-05-29 01:11 UTC, muncool39 commented on src/main/java/com/openbook/openbook/eventmanager/EventManagerService.java
> +            Page<Booth> booths = boothRepository.findAllBoothByEventId(pageable, eventId);
이벤트 관리자만 조회 가능해야 되기 때문에 이벤트id를 가져온 후 현재 로그인한 유저와 이벤트 생성자가 일치하는지 확인하는 과정도 존재해야 할 것 같습니다 !

2024-05-29 01:48 UTC, gitseoyeon commented on src/main/java/com/openbook/openbook/eventmanager/dto/BoothMangeData.java
> +public record BoothMangeData(
원래 manage가 맞습니다! 단순 오타가 났네요 수정하겠습니다 🥲

2024-05-29 03:19 UTC, gitseoyeon commented on src/main/java/com/openbook/openbook/eventmanager/dto/BoothMangeData.java
네! 이부분에 있어서는 제가 잘못 작성한 것 같아 수정했습니다!
<img width="413" alt="image" src="https://github.com/Project-OpenBook/openbook-server/assets/126096318/11a6418a-6ffc-4ffd-aaaf-a29f7b3e53a8">

2024-05-29 03:20 UTC, gitseoyeon commented on src/main/java/com/openbook/openbook/eventmanager/EventManagerService.java
> +            default -> throw new OpenBookException(HttpStatus.BAD_REQUEST, "잘못된 요청 값 입니다.");
넵 우선 먼저 작성하신 오류 메세지로 통일하겠습니다!

2024-05-29 03:21 UTC, gitseoyeon commented on src/main/java/com/openbook/openbook/eventmanager/EventManagerService.java
> +            Page<Booth> booths = boothRepository.findAllBoothByEventId(pageable, eventId);
로그인 한 유저의 토큰 값을 이용해서 해당 행사 관리자가 맞는지 판별하는 부분을 추가했습니다!

<img width="549" alt="image" src="https://github.com/Project-OpenBook/openbook-server/assets/126096318/0a115db0-f82f-411d-8e25-f2d35f947d77">

2024-05-29 03:22 UTC, gitseoyeon commented on src/main/java/com/openbook/openbook/eventmanager/EventManagerService.java
> +            Page<Booth> booths = boothRepository.findAllBoothByEventId(pageable, eventId);
> 로그인 한 유저의 토큰 값을 이용해서 해당 행사 관리자가 맞는지 판별하는 부분을 추가했습니다!
> 
> <img alt="image" width="549" src="https://private-user-images.githubusercontent.com/126096318/334636770-0a115db0-f82f-411d-8e25-f2d35f947d77.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY5NTMxNjksIm5iZiI6MTcxNjk1Mjg2OSwicGF0aCI6Ii8xMjYwOTYzMTgvMzM0NjM2NzcwLTBhMTE1ZGIwLWY4MmYtNDExZC04ZTI1LWYyZDM1Zjk0N2Q3Ny5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTI5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyOVQwMzIxMDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lZDkzMTUzZDc2ZmY0MmM5ZDlkMzQzNWY1ZWY0YWQyYTkzYzE2MzFiNzIzNThiMmRiNjRmYzVkOWY1MzYwMTNjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Qk2eexGvCCDwBmpOhRPLU_kjRDwaz-1OGPifZIMiZMo">

이 오류 메세지는 제가 우선 임의로 넣어본 메세지인데 혹시 더 좋은 오류 메세지가 있다면 말씀해주세요!

2024-05-29 03:50 UTC, muncool39 reviewed
확인했습니다 !! 수고하셨습니다 👍 
의견 하나 낸 것만 같이 생각해보면 좋을 것 같아요 !

2024-05-29 03:50 UTC, muncool39 commented on src/main/java/com/openbook/openbook/eventmanager/EventManagerService.java
> +        }
이 과정에서 Optional로 return되는 event를 검증 후 가져와서 사용하고
이후 부스를 찾을 때도 id대신 해당 Event를 사용하는 건 어떨까요?

2024-05-29 07:31 UTC, muncool39 approved these changes
확인했습니다 ! 수고하셨습니다 👍
추가로 생각난 건 linked_event를 찾을 때, :=event 말고 eventId로 비교해서 찾으셨길래 뭐가 더 나은지 검색해 보니까 id에 인덱싱을 하는 등.. 더 빠르게 조회가 가능하더라구요~
해당 내용(인덱싱, 쿼리문 등) 관련해서도 생각해보고 리팩토링하면 좋을 것 같습니다!😄

2024-05-29 07:44 UTC, gitseoyeon commented
> 확인했습니다 ! 수고하셨습니다 👍 추가로 생각난 건 linked_event를 찾을 때, :=event 말고 eventId로 비교해서 찾으셨길래 뭐가 더 나은지 검색해 보니까 id에 인덱싱을 하는 등.. 더 빠르게 조회가 가능하더라구요~ 해당 내용(인덱싱, 쿼리문 등) 관련해서도 생각해보고 리팩토링하면 좋을 것 같습니다!😄

아 그 사항에 대해서는 객체를 쿼리에 가져와서 비교하는 것보다 최소한의 필요한 정보인 id 만 불러와서 쿼리문에 적용하는게 더 빠를 거 같다고 생각해서 적용시켜보았습니다! 하지만 단순히 제가 스스로 생각해서 작성한 것이기 때문에 정말 빠른지는 사실 정확하지 않았었습니다 😅 직접 찾아보고 알려주셔서 감사합니다!!

2024-05-29 07:44 UTC, merged