Feat: 부스 등록시 행사 구역 테이블에 부스 아이디 등록
Project-OpenBook/openbook-server pull request #36
Opened 2024-05-27 05:27 UTC by gitseoyeon

## Summary

- closed #34
행사 구역 테이블에 부스 아이디 칼럼을 추가해 등록시 해당 부스의 아이디가 등록되도록 했습니다.
## Key Changes

- EventLayoutAreaService에 registrationBooth() 메서드를 추가해서 부스 아이디가 저장되도록 했습니다.
- EventLayoutArea에 updateBooth 메서드를 추가해서 null 이었던 값을 등록 신청한 부스의 아이디로 바뀌게 했습니다.
## Testing

- 부스 신청시 행사 구역 위치 테이블에 들어가는 모습
<img width="622" alt="image" src="https://github.com/Project-OpenBook/openbook-server/assets/126096318/e54177e8-6eca-4fc4-a996-4e301496dce5">

## To Reviewers

- EventLayoutArea에 부스 칼럼을 추가할 때 기본 값이 null 이기 때문에 상태 기본 값을 PrePersist 어노테이션으로 지정한 것처럼 null 값 또한 이 어노테이션을 사용해야 하나 고민했으나 현재 사용하지 않아도 크게 문제 없이 작동하기에 따로 선언하지는 않았습니다!
- EventLayoutAreaService 에서 새로 추가한 registrationBooth 메서드가 작동하는 시점에서는 이미 부스가 신청한 위치가 이미 예약된 자리인지 아닌지 이전에 오류 처리를 했기 때문에 따로 한번더 오류 처리를 하지 않았습니다. 혹시 따로 필요하다 싶으시다면 말씀해주세요!
- 이외에도 질문사항이나 의견 있으시면 말씀 부탁드립니다 !

2024-05-27 06:27 UTC, muncool39 requested changes
수고하셨습니다 ~ 
저희가 boothLocation 대신 area에 부스 필드를 추가해, 그걸 수정하는 방향으로 구현한다고 생각하는데, 현재 BoothLocationService 에서 area 상태 확인과 업데이트가 진행되고 있어서 해당 부분을 수정하면 더 좋을 것 같습니다.
생각난 방법을 제시해보겠습니다!
- U...AreaService 에 status 확인 메서드를 추가합니다.
ex) isUnselectable : status가 모두 Empty면 false, 아니면 true를 return
- UserBooth 서비스에서 이를 받아 오류를 처리합니다.
```java
if(isUnselectable) -> throw 에러
```
결과적으로 이 과정에서 BoothLocationService는 사용하지 않도록 변경합니다.

또 이전 메서드에서는 확인과 동시에 상태를 WAITING으로 업데이트했는데, 해당 과정을 분리시키는 것이 좋을 것 같습니다! 
area의 부스를 업데이트하면서 상태를 함께 변경시키는 것이 좋을 것 같습니다. 이유는 booth가 업데이트 되는 경우, status도 항상 함께 변경되기 때문입니다. 
ex) EventLayoutArea 의 `updateBooth(b)` 동작 -> `updateBoothStatus(s, b)` 로 합쳐서 변경

추가적으로 생각난 건, 현재 부스 등록 request dto 에 예약하고자 하는 자리 변수명이 location이라 헷갈릴 수 있다고 생각해서, layoutArea라고 변경하는 것도 방법이 될 수 있을 것 같습니다 !

2024-05-27 06:36 UTC, muncool39 commented on src/main/java/com/openbook/openbook/event/entity/EventLayoutArea.java
> +    private Booth booth;
연결된 배치도나 행사같은 경우, linked~ 로 사용하고 있기 때문에,
해당 필드로 linkedBooth 로 변경하는 게 일관성면에서 좋을 것 같아요!

2024-05-27 06:36 UTC, muncool39 commented on src/main/java/com/openbook/openbook/basicuser/service/UserEventLayoutAreaService.java
> +            EventLayoutArea layoutArea = eventLayoutArea.get();
To Reviewers 부분에서 말씀하신 것에 관해서, 작성하신 것처럼 따로 확인하지 않아도 된다고 생각합니다!
그래서 해당 부분을 한 줄로 바로 가져와도 될 것 같아요!
ex)
```java
 EventLayoutArea layoutArea = layoutAreaRepository.findById(id).get();
```

2024-05-27 07:37 UTC, gitseoyeon commented
> 수고하셨습니다 ~ 저희가 boothLocation 대신 area에 부스 필드를 추가해, 그걸 수정하는 방향으로 구현한다고 생각하는데, 현재 BoothLocationService 에서 area 상태 확인과 업데이트가 진행되고 있어서 해당 부분을 수정하면 더 좋을 것 같습니다. 생각난 방법을 제시해보겠습니다!
> 
> * U...AreaService 에 status 확인 메서드를 추가합니다.
>   ex) isUnselectable : status가 모두 Empty면 false, 아니면 true를 return
> * UserBooth 서비스에서 이를 받아 오류를 처리합니다.
> 
> ```java
> if(isUnselectable(..)) -> throw 에러
> ```
> 
> 결과적으로 이 과정에서 BoothLocationService는 사용하지 않도록 변경합니다.
> 
> 또 이전 메서드에서는 확인과 동시에 상태를 WAITING으로 업데이트했는데, 해당 과정을 분리시키는 것이 좋을 것 같습니다! area의 부스를 업데이트하면서 상태를 함께 변경시키는 것이 좋을 것 같습니다. 이유는 booth가 업데이트 되는 경우, status도 항상 함께 변경되기 때문입니다. ex) EventLayoutArea 의 `updateBooth(b)` 동작 -> `updateBoothStatus(s, b)` 로 합쳐서 변경
> 
> 추가적으로 생각난 건, 현재 부스 등록 request dto 에 예약하고자 하는 자리 변수명이 location이라 헷갈릴 수 있다고 생각해서, layoutArea라고 변경하는 것도 방법이 될 수 있을 것 같습니다 !

좋은 조언 감사합니다! 저는 부스 등록시 boothlocation 정보는 저장되어야 한다고 이해하고 작성하다보니 이슈가 생긴 것 같습니다! 말씀하신 것을 바탕으로 수정해보았으니 혹시 제가 잘못이해하거나 수정해야할 일이 있으면 편하게 말씀해주세요!

2024-05-27 08:01 UTC, muncool39 requested changes
의견 반영해주셔서 감사합니다!!😭 추가로 의견 작성했습니다 !
혹시라도 이해 안되시는 부분 있으시면 물어봐주세요 !!

2024-05-27 08:01 UTC, muncool39 commented on src/main/java/com/openbook/openbook/basicuser/service/UserEventLayoutAreaService.java
자리가 있는지 확인하는 해당 메서드를 linkedBooth 가 아닌 areaStatus로 확인하면 될 것 같아요!! 
그래서 boothLocationApplication에 작성하신 부분만 가져오시면 된다고 생각합니다 ! 
ex) 밑 메서드를 참고
```java
public boolean hasReservationData(List<Long> eventLayoutAreaIdList){
        for(Long areaId: eventLayoutAreaList){
            Optional<EventLayoutArea> eventLayoutArea = eventLayoutAreaRepository.findById(areaId);
            EventLayoutArea layoutArea = eventLayoutArea.get();
            if(status가 empty가 아닌 경우){
                return true;
            }
        }
	return false;
    }
```
이 메서드만 써서 자리가 예약 가능한지 확인하고, 예약이 가능하다면 부스 생성을 진행하고 area 정보를 업데이트 하면 될 것 같습니다 !!
현재 코드가 예약 가능한지 hasReservationData에서 검증하고 boothLocationApplication에서 검증을 또 하고 있는데,
이후 업데이트 하는 메서드에서는 따로 검증 없이 업데이트하는 기능만 넣으면 될 것 같습니다 !
ex)
```java
public void regis...(List<Long> areas, Booth booth){
        for(Long areaId : areas){
            EventLayoutArea eventLayoutArea = layoutAreaRepository.findById(areaId).get();
	    eventLayoutArea.updateBoothStatus(EventLayoutAreaStatus.WAITING, booth);
        }
    }
```

2024-05-27 08:01 UTC, muncool39 commented on src/main/java/com/openbook/openbook/event/entity/EventLayoutArea.java
> +
status만 update 하는 경우도 있기 때문에 (부스 승인 시에는 상태만 승인으로 바꾸면 되지 않을까요?!) status, booth로 나누고 부스를 업데이트 하는 쪽에만 status를 함께 업데이트 하도록 해도 좋을 것 같아요!

2024-05-27 08:01 UTC, muncool39 commented on src/main/java/com/openbook/openbook/event/repository/EventLayoutAreaRepository.java
> +    Long findBoothById(Long areaId);
혹시 해당 메서드가 어디에 사용되고 있을까요?! 코드를 보는데 찾지 못해서 여쭤봅니다!!

2024-05-27 13:55 UTC, gitseoyeon commented on src/main/java/com/openbook/openbook/event/repository/EventLayoutAreaRepository.java
> +    Long findBoothById(Long areaId);
앗 ㅋㅋㅋㅋ 불필요한 제거해야하는 코드였는데 실수로 못지웠습니다! 다시 수정해서 올렸습니다~~

2024-05-27 14:14 UTC, muncool39 requested changes
확인 후 리뷰 남겼습니다 ! 😭

2024-05-27 14:14 UTC, muncool39 commented on src/main/java/com/openbook/openbook/basicuser/service/UserEventLayoutAreaService.java
> +            EventLayoutArea eventLayoutArea = layoutAreaRepository.findById(id).get();
혹시 layoutArea의 id가 존재하는 id인지 확인하는 과정이 어디 위치하는지 알 수 있을까요?!
어디서 확인 과정을 거쳐서 여기서는 바로 get으로 가져온다고 이해했는데 해당 내용이 어디있는지 제가 못찾아서 여쭤봅니다!😭

2024-05-27 14:14 UTC, muncool39 commented on src/main/java/com/openbook/openbook/basicuser/dto/request/BoothRegistrationRequest.java
> +        @NotNull @Size(min = 1, max = 3) List<Long> layoutArea,
여러 값이 들어올 수 있기 때문에 s를 붙여도 괜찮을 것 같네요!

2024-05-27 14:14 UTC, muncool39 commented on src/main/java/com/openbook/openbook/basicuser/service/BoothLocationService.java
해당 파일을 아예 삭제해도 괜찮을 것 같네요!

2024-05-27 14:14 UTC, muncool39 commented on src/main/java/com/openbook/openbook/basicuser/service/UserEventLayoutAreaService.java
> +    }
해당 메서드 관련해 의견 남깁니다!
- request.layoutArea() 를 첫번째 변수로 넘기기 때문에 매개변수 명도 비슷하게 변경하는 건 어떨까요?
- for 문 안의 layoutId가 LayoutArea의 id일 텐데, Layout이라는 엔티티가 존재하기 때문에 해당 id랑 헷갈릴 가능성도 있을 것 같아서 areaId 등으로 알기 쉽게 변경하는건 어떨까요?
- 메서드 명도 좀 더 의미가 알기 쉽도록 변경하는 건 어떨까요?

2024-05-27 14:14 UTC, muncool39 commented on src/main/java/com/openbook/openbook/basicuser/service/UserEventLayoutAreaService.java
> +            }
모든 area의 status가 EMPTY 여야 하는데, 해당 로직대로라면 첫번째만 EMPTY여도 false 가 리턴되기 때문에
여기서는 empty가 아닌걸 체크하고 모두 통과하면 밑에서 false를 return해야 될 것 같습니다!

2024-05-27 16:11 UTC, gitseoyeon commented on src/main/java/com/openbook/openbook/basicuser/service/UserEventLayoutAreaService.java
> +            EventLayoutArea eventLayoutArea = layoutAreaRepository.findById(id).get();
행사 배치도에서 바로 선택해서 데이터를 가져온다고 생각했기 때문에 따로 layoutArea id가 존재하는 id인지 확인하는 과정은 작성하지 않았었습니다! 위치를 선택할 때 피그마를 확인해보니 데이터를 입력하는 창을 클릭하면 모달창이 열리게 되고 그 과정에서 바로 위치 id를 가져오는 것이라 당연히 부스 배치도 상에서는 존재하는 id 이지 않을까 싶어 확인 과정을 넣지는 않았습니다. 혹시 필요하다면 따로 작성해서 수정하겠습니다!
<img width="435" alt="image" src="https://github.com/Project-OpenBook/openbook-server/assets/126096318/213403da-71c3-4b4c-9782-5fb89f0384b1">

2024-05-27 16:43 UTC, gitseoyeon commented on src/main/java/com/openbook/openbook/basicuser/service/UserEventLayoutAreaService.java
> +    }
매개 변수 명과 변수 명은 layoutAreas와 layoutAreaId로 변경하고 있는데, 메서드 명과 같은 경우는 파파고 번역으로 나온 메서드 명이었습니다! 부스 위치를 신청한다는 의미에서 requestBoothLocation 으로 변경하는건 어떨까요?!

2024-05-27 17:05 UTC, muncool39 commented on src/main/java/com/openbook/openbook/basicuser/service/UserEventLayoutAreaService.java
> +            EventLayoutArea eventLayoutArea = layoutAreaRepository.findById(id).get();
앗 그렇군요 감사합니다! postman으로 테스트 할 경우 등을 생각하면 있어도 좋을 것 같은데 실제 서비스에서 쓴다고 하면 말씀해주신 것처럼 꼭 필요한 부분은 아닐 것 같네요 ㅎㅎ

2024-05-28 04:19 UTC, muncool39 approved these changes
변경 사항 확인했습니다! 수고 많으셨습니다! 😭
병합 전에 하나 의견이 있는데, 커밋 메세지를 pr 에 작성하신 대로도 좋지만
Fix: 부스 등록 시 구역 정보가 저장되지 않는 문제
같이 해결한 문제를 적는 방법도 좋을 것 같아요!
접두사가 Fix인 만큼 Fix 내용을 적는 건 어떨까요?

2024-05-28 05:52 UTC, gitseoyeon commented
> 변경 사항 확인했습니다! 수고 많으셨습니다! 😭 병합 전에 하나 의견이 있는데, 커밋 메세지를 pr 에 작성하신 대로도 좋지만 Fix: 부스 등록 시 구역 정보가 저장되지 않는 문제 같이 해결한 문제를 적는 방법도 좋을 것 같아요! 접두사가 Fix인 만큼 Fix 내용을 적는 건 어떨까요?

좋습니다! 처음에는 feat으로 작성하다보니 저렇게 작성하고 수정하지 않았던 것 같습니다! 참고하겠습니다 😊

2024-05-28 05:55 UTC, merged