Feat: 부스 등록 신청 상태 변경 API
Project-OpenBook/openbook-server pull request #43
Opened 2024-05-29 17:12 UTC by gitseoyeon

## Summary

- closed #39 
해당 행사에 등록을 신청한 부스들의 상태를 변경하는 API 입니다.
## Key Changes

- 변경 요청할 부스 상태 데이터를 담는 record 클래스 추가했습니다.
- 이미 승인 / 반려된 상태의 부스를 다시 승인 / 반려 요청했을 경우에 오류를 반환하도록 했습니다.
## Testing

- 승인 / 반려 를 했을 경우
![image](https://github.com/Project-OpenBook/openbook-server/assets/126096318/829493a3-5ead-4750-80b7-b4d70bddcec4)

- 승인되었거나 반려된 부스에 같은 상태의 데이터를 다시 요청할 경우
![image](https://github.com/Project-OpenBook/openbook-server/assets/126096318/c7c7e421-6712-4416-a20a-7017c2da74d5)

## To Reviewers

- 현재 작성한 controller 클래스에 존재하는 엔드포인트에 관련해서 올바르게 작성한건지 살짝 의문이 들어 의견 나누면 좋겠다 생각합니다!
- 외에도 다른 수정사항이나 질문사항있으시면 말씀해주세요~

2024-05-30 07:12 UTC, muncool39 requested changes
확인했습니다 !😃
엔드포인트 관련해서도 리뷰 남겼습니다~

2024-05-30 07:12 UTC, muncool39 commented on src/main/java/com/openbook/openbook/eventmanager/EventManagerController.java
> +    public ResponseEntity<ResponseMessage> changeBoothStatus(@PathVariable Long boothId,
파라미터 관련해서, 현재 로그인한 유저가 해당 부스가 신청한 행사의 관리자인지 확인하는 과정이 필요하기 때문에 Authentication 정보도 받아야 할 것 같습니다~

2024-05-30 07:12 UTC, muncool39 commented on src/main/java/com/openbook/openbook/eventmanager/EventManagerController.java
> +    @PostMapping("/booths/{boothId}/status")
http 관련해서, 저는 put을 사용하긴 했는데 사실 저도 post를 사용할지 고민을 많이 했어서
이 부분은 의견 나누고 통일시키면 좋을 것 같네요! 서연님이 post를 고르신 이유가 궁금합니다 !
경로는 지금도 의미가 통해서 괜찮다고 생각합니다! 추가하자면 이벤트 관리에 포함되는걸 나타내려면 앞에 events 등을 붙여도 좋을 것 같네요~

2024-05-30 07:12 UTC, muncool39 commented on src/main/java/com/openbook/openbook/eventmanager/EventManagerService.java
> +                }
해당 area 상태를 업데이트 하는 과정은 메서드로 분리시키고
매개변수로 EventLayoutAreaStatus를 넘겨서 해당 메서드에서 처리하도록 리팩터링 해도 좋을 것 같습니다 ~

2024-05-30 07:12 UTC, muncool39 commented on src/main/java/com/openbook/openbook/eventmanager/EventManagerService.java
부스 상태를 변경할 때, 부스에 연결된 행사의 매니저가 현재 로그인한 유저와 일치하는지 확인하는 과정이 필요할 것 같습니다 !

2024-05-30 07:12 UTC, muncool39 commented on src/main/java/com/openbook/openbook/eventmanager/EventManagerService.java
> +        if(!booth.getStatus().equals(boothStatus)){
동일하면 바로 exception 을 발생시키게 하고,
그 밑에 else문 없이 부스 상태 변경 로직을 작성해도 좋을 것 같아요~

2024-05-30 07:41 UTC, gitseoyeon commented on src/main/java/com/openbook/openbook/eventmanager/EventManagerController.java
> +    @PostMapping("/booths/{boothId}/status")
사실 지금 개발 방향으로 봤을 땐 put을 사용하는게 제가 생각하기에도 옳다고 생각합니다!  
post와 put에 대해 고민하다가 post로 사용하게 된 이유는 부스가 승인 되었을 때 boothLocation에 부스 정보가 저장될 지에 대해 
명확하게 정하고 다시 수정하면 좋을 거 같아서 우선 post로 두긴 했습니다!

최근에 잠깐 논의 해봤을 때는 eventLayoutArea에 부스 정보가 저장되면서 boothLocation에는 따로 저장할 필요가 없다고 이야기가 나왔던 것 같아서 이대로 계속 저장하지 않고 eventLayoutArea의 부스 정보만 활용해도 좋을 거 같긴 합니다! 이 방향대로 개발하게 된다면 노션에 명시된 api 명세서도 수정하면 좋을 것 같습니다 😊

2024-05-30 08:01 UTC, gitseoyeon commented on src/main/java/com/openbook/openbook/eventmanager/EventManagerController.java
> +    public ResponseEntity<ResponseMessage> changeBoothStatus(@PathVariable Long boothId,
신청한 행사의 관리자인지 판별하기 위해 이벤트 아이디 정보도 PathVariable 어노테이션을 이용해서 추가하는게 좋을까요?

2024-05-30 09:14 UTC, muncool39 commented on src/main/java/com/openbook/openbook/eventmanager/EventManagerController.java
> +    public ResponseEntity<ResponseMessage> changeBoothStatus(@PathVariable Long boothId,
그 방법도 있겠고, eventid를 포함하지 않고 booth 안에 연결된 행사 정보를 사용하는 방법도 있을 것 같습니다~

2024-05-31 08:34 UTC, gitseoyeon commented
우선 의견 내주신 변동 사항에 있어서는 리팩터링을 완료했습니다! 그리고 http 메서드 관련해서는 우선 현재 개발 방향에 맞게 put으로 변경하는게 맞는 것 같아서 변경했습니다!

2024-05-31 09:38 UTC, muncool39 reviewed
변경 수고하셨습니다!👍
코멘트로 궁금한 점을 남겼습니다!

2024-05-31 09:38 UTC, muncool39 commented on src/main/java/com/openbook/openbook/eventmanager/EventManagerService.java
> +    }
사실 제가 생각한 방향은 BoothStatus를 사용한 if 판단을 위에서 하고, 넘길 때 EventLayoutAreaStatus를 줘서 for문에 해당 변수를 사용하는 느낌이였는데 (같은 for문이 반복된다고 생각해서 판단은 위에서 하고 메서드명 그대로 AreaStatus만 바꾸는 걸 생각했습니다!) 
이와 관련해서는 어떻게 생각하실까요?! 코드에 정답은 없으니 따로 괜찮다 생각하시는 대로 하셔도 될 것 같습니다~ 일단 의견만 내봐요!

2024-05-31 09:38 UTC, muncool39 commented on src/main/java/com/openbook/openbook/eventmanager/EventManagerController.java
> +    @PutMapping("/booths/{boothId}/status")
엔드포인트 관련해 이전 리뷰에서
이벤트 관리에 포함되는걸 나타내려면 앞에 events 등을 붙여도 좋을 것 같다~고 했는데
혹시 이와 관련해서는 어떻게 생각하실까요?

2024-05-31 09:58 UTC, gitseoyeon commented on src/main/java/com/openbook/openbook/eventmanager/EventManagerService.java
> +    }
아 ~~ 제가 이해를 잘못하고 있었네요! 그렇게 진행하면 비슷한 코드가 차지하는 비율이 확실히 줄어서 좋을거같아요!

2024-05-31 10:01 UTC, gitseoyeon commented on src/main/java/com/openbook/openbook/eventmanager/EventManagerController.java
> +    @PutMapping("/booths/{boothId}/status")
앗 그 리뷰에 대해서는 제가 까먹고 수정을 못했었는데 부스 신청 목록 엔드포인트와 통일성을 주기위해 events/booths/{boothId}/status 로 주면 깔끔할 거 같은데 괜찮을까요?

2024-05-31 10:32 UTC, gitseoyeon commented
엔드포인트와 메서드 분리 관련해서 수정을 마쳤습니다! 메서드 분리 관련돼서 말씀하신 걸로 제가 잘 이해한건지는 모르겠지만 우선 비슷한 흐름의 for문의 중복 코드는 줄였습니다!

2024-05-31 11:04 UTC, muncool39 approved these changes
변경 확인했습니다! 수고하셨습니다!😭

2024-05-31 11:05 UTC, muncool39 commented on src/main/java/com/openbook/openbook/eventmanager/EventManagerController.java
> +    @PutMapping("/booths/{boothId}/status")
좋다고 생각합니다 !👍

2024-05-31 13:20 UTC, merged